const REIS = {
  meta: {
    titel: "Indonesië 2026",
    reiziger: "Wouter & gezelschap",
    noodcontact: "+31 6 xx xxx xxx",
  },

  locaties: [
    {
      id: "jakarta",
      stad: "Jakarta",
      land: "Indonesië — Java",
      type: "stad",
      emoji: "🏙️",
      coordinaten: { lat: -6.2088, lng: 106.8456 },
      datums: { aankomst: "2026-08-23", vertrek: "2026-08-25" },
      hotel: {
        naam: "Jambuluwuk Thamrin Hotel",
        adres: "Jl. M.H. Thamrin, Jakarta Pusat",
        mapsUrl: "https://maps.google.com/?q=Jambuluwuk+Thamrin+Hotel+Jakarta",
        coordinaten: { lat: -6.1944, lng: 106.8229 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€55",
        ontbijt: "inbegrepen",
        annulering: "vóór 18 augustus",
        opmerkingen: "✅ Al betaald. Aankomst ~14:50 plaatselijke tijd. Taxi vanaf vliegveld ~30 min.",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Amsterdam AMS",
          vluchtnummer: "Vul vluchtnummer in",
          aankomstTijd: "2026-08-23T14:50:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "Soekarno-Hatta Airport (CGK). Bluebird taxi naar hotel ~30 min, ~Rp 150.000. Geen onofficiële taxichauffeurs meegaan.",
        },
        vertrek: {
          type: "trein",
          naar: "Yogyakarta",
          vertrekTijd: "2026-08-25T08:00:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "~6,5 uur treinreis. Tickets via astrindotour.co.id. Vertrekstation: Jakarta Gambir.",
        },
      },
      activiteiten: [
        {
          naam: "Kota Tua — Fatahillah Square",
          categorie: "bezienswaardigheden",
          duur: "2–3 uur",
          kosten: "gratis",
          coordinaten: { lat: -6.1352, lng: 106.8133 },
          tip: "Het koloniale hart van Jakarta. Centraal plein vol straatleven. Bezoek Café Batavia (iconisch koloniaal café uit 1805) en Museum Bank Indonesia.",
          mapsUrl: "https://maps.google.com/?q=Fatahillah+Square+Jakarta",
        },
        {
          naam: "Museum Bank Indonesia",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "Rp 5.000",
          coordinaten: { lat: -6.1366, lng: 106.8126 },
          tip: "Modern museum over de handelsgeschiedenis van Indonesië en de VOC. Loopafstand van Fatahillah Square.",
          mapsUrl: "https://maps.google.com/?q=Museum+Bank+Indonesia+Jakarta",
        },
        {
          naam: "Istiqlal Moskee + Jakarta Cathedral",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "gratis",
          coordinaten: { lat: -6.1698, lng: 106.8300 },
          tip: "Grootste moskee van Zuidoost-Azië recht tegenover een katholieke kathedraal — symbool voor religieuze tolerantie. Schouders en knieën bedekken.",
          mapsUrl: "https://maps.google.com/?q=Istiqlal+Mosque+Jakarta",
        },
        {
          naam: "Glodok (Chinese wijk)",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "gratis",
          coordinaten: { lat: -6.1479, lng: 106.8178 },
          tip: "Oudste Chinese wijk van Jakarta. Levendig en chaotisch met Chinese tempels en avondmarktjes. Wordt het levendigst vanaf 17:00.",
          mapsUrl: "https://maps.google.com/?q=Glodok+Jakarta",
        },
        {
          naam: "Henshin Rooftop Bar",
          categorie: "bezienswaardigheden",
          duur: "2 uur",
          kosten: "€€€€",
          coordinaten: { lat: -6.2136, lng: 106.8198 },
          tip: "Luxe rooftop bar met spectaculair panorama over de skyline. Perfect voor de avond. Eventueel vooraf reserveren.",
          mapsUrl: "https://maps.google.com/?q=Henshin+Bar+Jakarta",
        },
        {
          naam: "MONAS (Nationaal Monument)",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          coordinaten: { lat: -6.1754, lng: 106.8272 },
          tip: "Iconische obelisk van 132m hoog. Neem de lift naar de top voor panoramisch uitzicht. 's Morgens vroeg voor minder wachtrij.",
          mapsUrl: "https://maps.google.com/?q=Monas+Jakarta",
        },
      ],
      restaurants: [
        {
          naam: "Namaaz Dining",
          keuken: "Indonesisch moleculair",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          afstand: "25 min taxi",
          adres: "Jl. Sriwijaya I No.40, Kebayoran Baru, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Namaaz+Dining+Jakarta",
          reservering: true,
          openingstijden: "18:30–23:00 (di–za)",
          tip: "Indonesische moleculaire gastronomie op topniveau. 16 verrassingsgerechten. Weken van tevoren reserveren — absoluut bijzonder.",
        },
        {
          naam: "Sate Khas Senayan",
          keuken: "Indonesisch",
          sfeer: "authentiek",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "15 min taxi",
          adres: "Jl. Kebon Sirih No.31A, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Sate+Khas+Senayan+Jakarta",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Beste sate van Jakarta. Bestel de sate kambing (geit). Contant betalen.",
        },
        {
          naam: "Café Batavia",
          keuken: "Internationaal / Koloniaal",
          sfeer: "historisch",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "20 min taxi (Kota Tua)",
          adres: "Jl. Pintu Besar Utara No.14, Kota Tua",
          mapsUrl: "https://maps.google.com/?q=Cafe+Batavia+Jakarta",
          reservering: false,
          openingstijden: "09:00–24:00",
          tip: "Iconisch koloniaal pand uit 1805 op Fatahillah Square. Goed voor lunch na Kota Tua.",
        },
        {
          naam: "Warung Nasi Ampera",
          keuken: "Sundanees",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "5 min lopen",
          adres: "Meerdere locaties in Jakarta",
          mapsUrl: "https://maps.google.com/?q=Warung+Nasi+Ampera+Jakarta",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Authentiek Sundanees eten. Wijs gewoon aan wat je wilt. Lokale favoriet, spotgoedkoop.",
        },
        {
          naam: "Kilo Kitchen",
          keuken: "Fusion / Modern Aziatisch",
          sfeer: "trendy",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "20 min taxi",
          adres: "Jl. Senopati No.53, Jakarta Selatan",
          mapsUrl: "https://maps.google.com/?q=Kilo+Kitchen+Jakarta",
          reservering: true,
          openingstijden: "12:00–22:00",
          tip: "Trendy restaurant met creatieve Aziatisch-geïnspireerde gerechten en cocktails. Populair bij locals. Reserveer van tevoren.",
        },
        {
          naam: "Bakmi GM",
          keuken: "Chinees-Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "10 min taxi",
          adres: "Meerdere vestigingen in Jakarta",
          mapsUrl: "https://maps.google.com/?q=Bakmi+GM+Jakarta",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Legendarische bakmi (noedelsoep) keten. Bestaat al decennialang. Bestel de bakmi ayam spesial. Spotgoedkoop.",
        },
      ],
    },

    {
      id: "yogyakarta",
      stad: "Yogyakarta",
      land: "Indonesië — Java",
      type: "cultuur",
      emoji: "🏯",
      coordinaten: { lat: -7.7956, lng: 110.3695 },
      datums: { aankomst: "2026-08-25", vertrek: "2026-08-29" },
      hotel: {
        naam: "Melia Purosani Yogyakarta",
        adres: "Jl. Suryotomo No.31, Yogyakarta",
        mapsUrl: "https://maps.google.com/?q=Melia+Purosani+Yogyakarta",
        coordinaten: { lat: -7.7930, lng: 110.3697 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€75,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 23 augustus",
        opmerkingen: "✅ Al betaald. Centraal gelegen, loopafstand tot Malioboro Street en Kraton.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Jakarta Gambir",
          opmerkingen: "~6,5 uur treinreis. Aankomst station Yogyakarta (Tugu). Taxi naar hotel ~10 min.",
        },
        vertrek: {
          type: "vlucht",
          naar: "Surabaya → Malang",
          vertrekTijd: "2026-08-29T07:00:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "Reisdag! Vliegtuig Yogyakarta → Surabaya, daarna trein naar Malang (~1:15 uur). Hele dag onderweg.",
        },
      },
      activiteiten: [
        {
          naam: "Borobudur Tempel ⚠️ Ticket vooraf kopen!",
          categorie: "cultuur",
          duur: "halve dag",
          kosten: "Rp 350.000",
          coordinaten: { lat: -7.6079, lng: 110.2038 },
          meenemen: ["structure temple climb ticket (vooraf online kopen!)", "zonnecrème", "hoofddeksel", "cash"],
          tip: "Grootste boeddhistische monument ter wereld. Ga bij zonsopgang. BELANGRIJK: 'Structure temple climb ticket' vooraf online kopen — ter plaatse niet altijd beschikbaar. ~1 uur rijden.",
          mapsUrl: "https://maps.google.com/?q=Borobudur+Temple",
        },
        {
          naam: "Prambanan Tempelcomplex ⚠️ Ticket vooraf",
          categorie: "cultuur",
          duur: "halve dag",
          kosten: "Rp 350.000",
          coordinaten: { lat: -7.7520, lng: 110.4914 },
          meenemen: ["ticket vooraf boeken", "cash", "comfortabele schoenen"],
          tip: "Indrukwekkend Hindoe-tempelcomplex. Ga vanaf 15:30 tot zonsondergang voor het mooiste licht. Bezoek ook Sewu Temple op loopafstand. ~30 min rijden.",
          mapsUrl: "https://maps.google.com/?q=Prambanan+Temple",
        },
        {
          naam: "Jomblang Cave (optioneel) ⚠️ Vooraf boeken",
          categorie: "avontuur",
          duur: "halve dag",
          kosten: "~Rp 450.000",
          coordinaten: { lat: -7.9583, lng: 110.6167 },
          meenemen: ["touwafdaling uitrusting (ter plaatse)", "stevige schoenen", "set droge kleding"],
          tip: "Spectaculaire touwafdaling in grot met een lichtstraal van boven ('heaven's light'). Vooraf boeken — beperkt aantal plekken per dag.",
          mapsUrl: "https://maps.google.com/?q=Jomblang+Cave+Yogyakarta",
        },
        {
          naam: "Mount Merapi Vulkaan",
          categorie: "avontuur",
          duur: "halve dag",
          kosten: "~Rp 400.000 p.p.",
          coordinaten: { lat: -7.5407, lng: 110.4458 },
          meenemen: ["stevige schoenen", "windjack", "zonnecrème"],
          tip: "Actieve vulkaan die in 2024 nog uitbarstte. Jeep-tour over lavastromen. Spectaculair. Boek via hotel.",
          mapsUrl: "https://maps.google.com/?q=Mount+Merapi+Yogyakarta",
        },
        {
          naam: "Malioboro Street",
          categorie: "winkelen",
          duur: "2 uur",
          kosten: "variabel",
          coordinaten: { lat: -7.7930, lng: 110.3672 },
          tip: "Bekendste straat van Yogya. Chaotisch en leuk, veel marktjes en straatmuzikanten. In de avond het leukst. Let op zakkenrollers.",
          mapsUrl: "https://maps.google.com/?q=Jalan+Malioboro+Yogyakarta",
        },
        {
          naam: "Prawirotaman (wijk)",
          categorie: "bezienswaardigheden",
          duur: "vrij",
          kosten: "variabel",
          coordinaten: { lat: -7.8200, lng: 110.3742 },
          tip: "Relaxte wijk vol cafés, massagesalons en restaurants. Goed voor een rustige avond.",
          mapsUrl: "https://maps.google.com/?q=Prawirotaman+Yogyakarta",
        },
        {
          naam: "Taman Sari (Waterpaleis)",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "Rp 15.000",
          coordinaten: { lat: -7.8100, lng: 110.3594 },
          tip: "Voormalig koninklijk waterpaleis met prachtige vijvers en tuinen. Loopafstand van het Kraton.",
          mapsUrl: "https://maps.google.com/?q=Taman+Sari+Yogyakarta",
        },
      ],
      restaurants: [
        {
          naam: "Restaurant Mediterranea By Kamil",
          keuken: "Mediterraans / Fusion",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "10 min taxi",
          adres: "Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Restaurant+Mediterranea+By+Kamil+Yogyakarta",
          reservering: true,
          openingstijden: "18:00–22:00",
          tip: "Overal terugkomend als toprestaurant in Yogya. ⚠️ Reserveren vanaf 2 maanden van tevoren — zo snel mogelijk boeken!",
        },
        {
          naam: "Bale Raos",
          keuken: "Javaans Paleis",
          sfeer: "authentiek",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "10 min lopen (Kraton)",
          adres: "Jl. Magangan Kulon No.1, Kraton, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Bale+Raos+Yogyakarta",
          reservering: true,
          openingstijden: "11:00–21:00",
          tip: "Gerechten uit de eeuwenoude sultanskeukens van het Kraton. Unieke, authentieke ervaring.",
        },
        {
          naam: "Via Via Restaurant",
          keuken: "Indonesisch / Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen (Prawirotaman)",
          adres: "Jl. Prawirotaman I No.30, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Via+Via+Restaurant+Yogyakarta",
          reservering: false,
          openingstijden: "08:00–23:00",
          tip: "Gezellig terras in Prawirotaman. Goede cocktails. Culturele optredens in de avond.",
        },
        {
          naam: "Gudeg Yu Djum",
          keuken: "Javaans",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "15 min taxi",
          adres: "Jl. Kaliurang KM 4.5, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Gudeg+Yu+Djum+Yogyakarta",
          reservering: false,
          openingstijden: "06:00–14:00",
          tip: "Beste gudeg (gestoofde jackfruit) van Yogya. Legendarisch. Kom vroeg want op = op.",
        },
        {
          naam: "Milas Restaurant",
          keuken: "Vegetarisch / Organisch",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "15 min lopen (Prawirotaman)",
          adres: "Jl. Prawirotaman I No.30A, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Milas+Restaurant+Yogyakarta",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Prachtige tuin met organische vegetarische gerechten. Een van de leukste terrassen van Yogya. Perfect voor lunch.",
        },
        {
          naam: "Angkringan Lik Man",
          keuken: "Javaans straateten",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Wongsodirjan, nabij Stasiun Tugu",
          mapsUrl: "https://maps.google.com/?q=Angkringan+Lik+Man+Yogyakarta",
          reservering: false,
          openingstijden: "17:00–02:00",
          tip: "Iconisch straatkraampje. Koffie met kaas, ketan (kleefrijst), sateetjes. Ultra-lokaal en ultra-goedkoop. 's Avonds een must.",
        },
      ],
    },

    {
      id: "malang",
      stad: "Malang",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "💧",
      coordinaten: { lat: -7.9839, lng: 112.6214 },
      datums: { aankomst: "2026-08-29", vertrek: "2026-09-01" },
      hotel: {
        naam: "Snooze Hostel Malang",
        adres: "Malang, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Snooze+Hostel+Malang",
        coordinaten: { lat: -7.9773, lng: 112.6265 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "⚠️ Betalen vóór 23 augustus!",
        bron: "booking.com",
        nachten: 3,
        prijsPerNacht: "€31,66",
        ontbijt: "niet inbegrepen",
        annulering: "vóór 26 augustus",
        opmerkingen: "⚠️ Nog betalen vóór 23 augustus!",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Yogyakarta → Surabaya (vlucht) → Malang (trein)",
          opmerkingen: "Reisdag. Vliegtuig Yogyakarta → Surabaya, daarna trein Surabaya → Malang (~1:15 uur).",
        },
        vertrek: {
          type: "trein",
          naar: "Probolinggo",
          opmerkingen: "~2,5 uur met de trein. Aankomst Probolinggo, taxi naar Bromo Park Hotel.",
        },
      },
      activiteiten: [
        {
          naam: "Tumpak Sewu Waterval ⚠️ Vervoer vooraf regelen",
          categorie: "natuur",
          duur: "hele dag",
          kosten: "~Rp 150.000 + chauffeur",
          coordinaten: { lat: -8.2317, lng: 112.9167 },
          meenemen: ["waterschoenen (verplicht!)", "zwemkleding", "handdoek", "cash voor tickets en chauffeur", "droge set kleren"],
          tip: "Mooiste waterval van Indonesië. Waterschoenen mee! Regel een privéchauffeur of tour via het hostel + park tickets vooraf kopen. ~3 uur rijden.",
          mapsUrl: "https://maps.google.com/?q=Tumpak+Sewu+Waterfall",
        },
        {
          naam: "Kajoetangan Heritage Village",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "gratis",
          coordinaten: { lat: -7.9812, lng: 112.6247 },
          tip: "Historische wijk met gerestaureerde koloniale straatjes en oude huizen. Goed voor foto's. Loopafstand van het hostel.",
          mapsUrl: "https://maps.google.com/?q=Kajoetangan+Heritage+Village+Malang",
        },
        {
          naam: "Idjen Boulevard",
          categorie: "bezienswaardigheden",
          duur: "1 uur",
          kosten: "gratis",
          coordinaten: { lat: -7.9701, lng: 112.6204 },
          tip: "Brede koloniale boulevard met prachtige oude villa's uit de Nederlandse tijd.",
          mapsUrl: "https://maps.google.com/?q=Ijen+Boulevard+Malang",
        },
        {
          naam: "Kampung Warna Warni Jodipan",
          categorie: "bezienswaardigheden",
          duur: "1 uur",
          kosten: "Rp 5.000",
          coordinaten: { lat: -7.9878, lng: 112.6367 },
          tip: "Kleurrijke regenboogwijk — arme wijk omgetoverd met vrolijke beschilderingen. Goed voor foto's.",
          mapsUrl: "https://maps.google.com/?q=Kampung+Warna+Warni+Jodipan+Malang",
        },
        {
          naam: "Kuneer Hill (Theegebied)",
          categorie: "natuur",
          duur: "halve dag",
          kosten: "variabel",
          coordinaten: { lat: -8.0500, lng: 112.5833 },
          meenemen: ["stevige schoenen", "windjack (hoger gelegen)"],
          tip: "Heuvelgebied met theeplantages en weids uitzicht. Goed alternatief als rustdag na de Tumpak Sewu tocht.",
          mapsUrl: "https://maps.google.com/?q=Coban+Rondo+Malang",
        },
      ],
      restaurants: [
        {
          naam: "Toko Oen",
          keuken: "Koloniale ijssalon",
          sfeer: "historisch",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Jend. Basuki Rachmat No.5, Malang",
          mapsUrl: "https://maps.google.com/?q=Toko+Oen+Malang",
          reservering: false,
          openingstijden: "09:00–21:00",
          tip: "Iconische koloniale ijssalon uit 1930. Beroemd om ijs en Nederlandse gebakjes. Een stukje geschiedenis.",
        },
        {
          naam: "Warung Bakso President",
          keuken: "Javaans / Lokaal",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "5 min lopen",
          adres: "Malang centrum",
          mapsUrl: "https://maps.google.com/?q=Bakso+President+Malang",
          reservering: false,
          openingstijden: "09:00–21:00",
          tip: "Malang staat bekend om bakso (gehaktballensoep). Dit is de meest legendarische plek van de stad.",
        },
        {
          naam: "Rawon Nguling",
          keuken: "Javaans",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "15 min taxi",
          adres: "Malang / omgeving",
          mapsUrl: "https://maps.google.com/?q=Rawon+Nguling+Malang",
          reservering: false,
          openingstijden: "09:00–16:00",
          tip: "Rawon is de zwarte rundvleessoep van Oost-Java (kleur van keluak-noot). Hier is de beste. Op = op, vroeg komen!",
        },
        {
          naam: "Depot Hasan — Ayam Goreng",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "10 min taxi",
          adres: "Malang centrum",
          mapsUrl: "https://maps.google.com/?q=Depot+Hasan+Malang",
          reservering: false,
          openingstijden: "10:00–21:00",
          tip: "Simpele warung met uitstekende gefrituurde kip (ayam goreng) en sambal. Dé lokale lunchplek.",
        },
        {
          naam: "Inggil Restaurant",
          keuken: "Javaans / Koloniaal",
          sfeer: "historisch",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Gajahmada No.4, Malang",
          mapsUrl: "https://maps.google.com/?q=Inggil+Restaurant+Malang",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Koloniaal pand met antieke Javaanse inrichting en goede traditionele gerechten. Sfeervolle avondlocatie.",
        },
      ],
    },

    {
      id: "bromo",
      stad: "Probolinggo (Bromo)",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "🌋",
      coordinaten: { lat: -7.9425, lng: 112.9530 },
      datums: { aankomst: "2026-09-01", vertrek: "2026-09-03" },
      hotel: {
        naam: "Bromo Park Hotel",
        adres: "Probolinggo, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Bromo+Park+Hotel+Probolinggo",
        coordinaten: { lat: -7.8344, lng: 113.2167 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Afschrijving 22 september",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€67",
        ontbijt: "inbegrepen",
        annulering: "vóór 24 augustus",
        opmerkingen: "Afschrijving vindt automatisch plaats op 22 september.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Malang",
          opmerkingen: "~2,5 uur trein. Taxi vanuit Probolinggo station naar hotel.",
        },
        vertrek: {
          type: "trein",
          naar: "Licin (via Banyuwangi)",
          opmerkingen: "~5 uur met trein en taxi. Trein naar Banyuwangi, taxi naar Licin.",
        },
      },
      activiteiten: [
        {
          naam: "Mount Bromo bij Zonsopgang",
          categorie: "natuur",
          duur: "hele ochtend (start 02:00!)",
          kosten: "Rp 220.000 (park) + jeep ~Rp 300.000",
          coordinaten: { lat: -7.9425, lng: 112.9530 },
          meenemen: ["WARME kleding (het is koud, ~5°C bij nacht!)", "sjaal of buff", "zaklamp / hoofdlamp", "stevige schoenen", "cash"],
          tip: "Actieve vulkaan. Vertrek om ~02:00 voor zonsopgang op het uitkijkpunt. Jeep regelen via hotel. Neem warme kleding mee — het is op 2.329m heel koud.",
          mapsUrl: "https://maps.google.com/?q=Mount+Bromo+East+Java",
        },
        {
          naam: "Madakaripura Waterval (omweg waard)",
          categorie: "natuur",
          duur: "2–3 uur",
          kosten: "Rp 25.000 + gids ~Rp 50.000",
          coordinaten: { lat: -7.9120, lng: 113.0444 },
          meenemen: ["waterschoenen of oude schoenen (je wordt nat!)", "zwemkleding", "droge kleren"],
          tip: "Majestueuze waterval van 200m hoog. Je loopt door een smalle kloof — het laatste stuk word je nat. Combineren met Bromo op dezelfde dag.",
          mapsUrl: "https://maps.google.com/?q=Madakaripura+Waterfall",
        },
        {
          naam: "Wandeling Cemoro Lawang naar Bromo krater",
          categorie: "avontuur",
          duur: "3 uur (6 km)",
          kosten: "inbegrepen bij parkticket",
          coordinaten: { lat: -7.9200, lng: 112.9500 },
          meenemen: ["stevige wandelschoenen", "zonnebrandcrème", "voldoende water"],
          tip: "Wandeling van 6 km vanuit Cemoro Lawang naar de kraterrand. Spectacular uitzicht. Eventueel paard huren voor een deel.",
          mapsUrl: "https://maps.google.com/?q=Cemoro+Lawang+Bromo",
        },
      ],
      restaurants: [
        {
          naam: "Café Lava Bromo",
          keuken: "Indonesisch / Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "45 min auto (bij vulkaan)",
          adres: "Cemoro Lawang, nabij Bromo",
          mapsUrl: "https://maps.google.com/?q=Cafe+Lava+Bromo",
          reservering: false,
          openingstijden: "06:00–21:00",
          tip: "Populair bij vulkaanbezoekers. Goed voor een warme kop koffie na de vroege ochtend op de vulkaan.",
        },
        {
          naam: "Warung bij het hotel",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "op het terrein",
          adres: "Bromo Park Hotel, Probolinggo",
          mapsUrl: "https://maps.google.com/?q=Bromo+Park+Hotel+Probolinggo",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "Ontbijt is inbegrepen. Neem 's avonds voor Bromo een stevige maaltijd zodat je om 02:00 genoeg energie hebt.",
        },
        {
          naam: "Lava View Lodge — Restaurant",
          keuken: "Indonesisch / Internationaal",
          sfeer: "uitzicht",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "45 min auto (Cemoro Lawang)",
          adres: "Cemoro Lawang, Bromo Tengger Semeru NP",
          mapsUrl: "https://maps.google.com/?q=Lava+View+Lodge+Bromo",
          reservering: false,
          openingstijden: "06:00–21:00",
          tip: "Direct uitzicht op de vulkaan. Goed voor ontbijt of warme koffie ná de zonsopgang. Neem cash mee — in het park geen pin.",
        },
      ],
    },

    {
      id: "ijen",
      stad: "Licin (Ijen)",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "🔥",
      coordinaten: { lat: -8.0631, lng: 114.2333 },
      datums: { aankomst: "2026-09-03", vertrek: "2026-09-05" },
      hotel: {
        naam: "Lintang Luku Tent Resort",
        adres: "Licin, nabij Banyuwangi, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Lintang+Luku+tent+resort+Licin",
        coordinaten: { lat: -8.0631, lng: 114.2333 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€82",
        ontbijt: "inbegrepen",
        annulering: "NIET annuleerbaar",
        opmerkingen: "✅ Al betaald. ⚠️ Kan NIET meer geannuleerd worden.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Probolinggo → Banyuwangi (trein) → Licin (taxi)",
          opmerkingen: "~5 uur. Trein naar Banyuwangi, daarna taxi naar Licin (~30 min).",
        },
        vertrek: {
          type: "auto",
          naar: "Kalibaru",
          opmerkingen: "~2 uur rijden naar Kalibaru. Taxi of private driver regelen.",
        },
      },
      activiteiten: [
        {
          naam: "Kawah Ijen Blue Fire (vertrek 23:00!)",
          categorie: "natuur",
          duur: "hele nacht + ochtend",
          kosten: "Rp 150.000 + gids aanbevolen",
          coordinaten: { lat: -8.0583, lng: 114.2422 },
          meenemen: ["WARME kleding (meerdere lagen)", "gasmasker (huur ter plaatse — verplicht!)", "zaklamp of hoofdlamp", "stevige wandelschoenen", "waterfles"],
          tip: "Het 'blue fire' (blauwe vlam) is ALLEEN 's nachts te zien door gaslekkage. Vertrek ~23:00 voor het blauwe vuur, wandeling 3 km omhoog (~1,5 uur). Blauw vuur verdwijnt na zonsopgang maar het kratermeer bij dag is ook spectaculair.",
          mapsUrl: "https://maps.google.com/?q=Kawah+Ijen+Banyuwangi",
        },
        {
          naam: "Ijen Turquoise Kratermeer bij zonsopgang",
          categorie: "natuur",
          duur: "zonsopgang (na blue fire tocht)",
          kosten: "inbegrepen bij ticket",
          coordinaten: { lat: -8.0583, lng: 114.2422 },
          tip: "Na de blue fire tocht zie je bij zonsopgang het grootste zure kratermeer ter wereld (turquoise kleur). Blijf na de blue fire voor dit uitzicht.",
          mapsUrl: "https://maps.google.com/?q=Ijen+Crater+Lake",
        },
      ],
      restaurants: [
        {
          naam: "Eethuis bij het resort",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "op het terrein",
          adres: "Licin, Banyuwangi",
          mapsUrl: "https://maps.google.com/?q=Licin+Banyuwangi",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "In Licin zijn weinig opties. Ontbijt is inbegrepen. Neem snacks mee voor de Ijen-nacht.",
        },
        {
          naam: "Warung di Banyuwangi",
          keuken: "Osing / Oost-Javaans",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "30 min auto (Banyuwangi stad)",
          adres: "Banyuwangi centrum",
          mapsUrl: "https://maps.google.com/?q=Banyuwangi+centrum",
          reservering: false,
          openingstijden: "08:00–21:00",
          tip: "Als je toch in Banyuwangi bent (treinstation), proef dan Sego Tempong — lokaal specialiteit van rijst, groenten en superscherpe sambal.",
        },
      ],
    },

    {
      id: "kalibaru",
      stad: "Kalibaru",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "☕",
      coordinaten: { lat: -8.2467, lng: 114.0867 },
      datums: { aankomst: "2026-09-05", vertrek: "2026-09-07" },
      hotel: {
        naam: "Villa Kendi",
        adres: "Kalibaru, Banyuwangi, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Villa+Kendi+Kalibaru",
        coordinaten: { lat: -8.2467, lng: 114.0867 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€27",
        ontbijt: "inbegrepen",
        annulering: "vóór 2 september",
        opmerkingen: "✅ Al betaald. ⚠️ BELANGRIJK: vervoer naar het hotel VAN TEVOREN aanvragen bij het hotel — moeilijk bereikbaar!",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Licin",
          opmerkingen: "~2 uur rijden. ⚠️ Vervoer vooraf aanvragen bij Villa Kendi — hotel is zonder eigen vervoer moeilijk te bereiken.",
        },
        vertrek: {
          type: "auto",
          naar: "Ubud (Bali)",
          opmerkingen: "Hele dag onderweg. Auto naar Ketapang haven → ferry naar Gilimanuk (Bali) → auto naar Ubud (~3,5 uur).",
        },
      },
      activiteiten: [
        {
          naam: "Koffieplantage rondleiding",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "variabel",
          coordinaten: { lat: -8.2467, lng: 114.0867 },
          tip: "Kalibaru staat bekend om koffieplantages. Vraag het hotel om een rondleiding. Je ziet hoe koffie, vanille en cacao worden verbouwd.",
          mapsUrl: "https://maps.google.com/?q=Coffee+Plantation+Kalibaru",
        },
        {
          naam: "Rustdag in de natuur",
          categorie: "natuur",
          duur: "vrij",
          kosten: "gratis",
          coordinaten: { lat: -8.2467, lng: 114.0800 },
          tip: "Na de intensieve Bromo- en Ijen-tochten is dit de ideale rustdag. Geniet van het groene berglandschap en de frisse lucht op ~600m hoogte.",
          mapsUrl: "https://maps.google.com/?q=Kalibaru+East+Java",
        },
      ],
      restaurants: [
        {
          naam: "Villa Kendi restaurant",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "op het terrein",
          adres: "Kalibaru, Oost-Java",
          mapsUrl: "https://maps.google.com/?q=Villa+Kendi+Kalibaru",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "In Kalibaru zijn weinig restaurants. Ontbijt is inbegrepen. Vraag het hotel om aanbevelingen voor lokale eetgelegenheden.",
        },
        {
          naam: "Warung Kopi — plantage café",
          keuken: "Koffie & snacks",
          sfeer: "casual",
          prijsniveau: "€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Kalibaru, omgeving",
          mapsUrl: "https://maps.google.com/?q=Kalibaru+koffie",
          reservering: false,
          openingstijden: "07:00–18:00",
          tip: "Vraag het hotel voor de beste lokale koffie. Kalibaru-koffie is bijzonder goed — je bent omringd door koffieplantages.",
        },
      ],
    },

    {
      id: "ubud",
      stad: "Ubud",
      land: "Bali",
      type: "natuur",
      emoji: "🌿",
      coordinaten: { lat: -8.5069, lng: 115.2625 },
      datums: { aankomst: "2026-09-07", vertrek: "2026-09-11" },
      hotel: {
        naam: "Alamdini Resort Ubud",
        adres: "Ubud, Bali",
        mapsUrl: "https://maps.google.com/?q=Alamdini+Resort+Ubud",
        coordinaten: { lat: -8.5136, lng: 115.2625 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "11:00",
        boekingsnummer: "Betalen bij accommodatie",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€46,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 5 september",
        opmerkingen: "Betaling bij aankomst. Cancel vóór 5 september.",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Kalibaru → ferry → Bali → Ubud",
          opmerkingen: "Hele reisdag. Auto naar Ketapang haven, ferry naar Gilimanuk (~45 min), auto naar Ubud (~3,5 uur).",
        },
        vertrek: {
          type: "ferry",
          naar: "Nusa Lembongan",
          vertrekTijd: "2026-09-11T09:00:00",
          opmerkingen: "~3 uur. Speedboot van Sanur Beach naar Nusa Lembongan. ⚠️ Speedboot paar dagen van tevoren reserveren!",
        },
      },
      activiteiten: [
        {
          naam: "Sidemen Dagtrip (8 sep)",
          categorie: "natuur",
          duur: "hele dag",
          kosten: "Rp 50.000 + auto",
          coordinaten: { lat: -8.4667, lng: 115.4167 },
          meenemen: ["comfortabele wandelschoenen", "zonnecrème", "cash"],
          tip: "Rustig dal met de mooiste rijstterrassen van Bali (rustiger dan Tegallalang). ~1,5 uur rijden. Wandeling door de velden sterk aanbevolen.",
          mapsUrl: "https://maps.google.com/?q=Sidemen+Bali",
        },
        {
          naam: "Tegallalang Rijstterrassen (9 sep)",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "~Rp 15.000",
          coordinaten: { lat: -8.4314, lng: 115.2761 },
          meenemen: ["cash voor lokale bijdragen", "camera"],
          tip: "Bekendste uitzicht van Bali. Ga vroeg (07:00) voor de drukte. Neem cash mee.",
          mapsUrl: "https://maps.google.com/?q=Tegallalang+Rice+Terrace",
        },
        {
          naam: "Kanto Lampo Waterval (10 sep)",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          coordinaten: { lat: -8.5003, lng: 115.3042 },
          meenemen: ["waterschoenen", "zwemkleding"],
          tip: "Water stroomt trapgewijs over de rotsen. Waterschoenen mee! Prachtig voor foto's.",
          mapsUrl: "https://maps.google.com/?q=Kanto+Lampo+Waterfall+Bali",
        },
        {
          naam: "Campuhan Ridge Walk",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "gratis",
          coordinaten: { lat: -8.5014, lng: 115.2537 },
          meenemen: ["water", "zonnecrème", "comfortabele schoenen"],
          tip: "Wandeling van 2 km over heuvelrug met uitzicht op groene valleien. Ga bij zonsopgang voor het mooiste licht.",
          mapsUrl: "https://maps.google.com/?q=Campuhan+Ridge+Walk+Ubud",
        },
        {
          naam: "Tibumana Waterval",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          coordinaten: { lat: -8.4444, lng: 115.3039 },
          meenemen: ["waterschoenen", "zwemkleding"],
          tip: "Mooiste en relatief rustige waterval van het Ubud-gebied. Minder bezoekers dan andere watervallen.",
          mapsUrl: "https://maps.google.com/?q=Tibumana+Waterfall+Bali",
        },
        {
          naam: "Ubud Monkey Forest",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 80.000",
          coordinaten: { lat: -8.5186, lng: 115.2593 },
          meenemen: ["geen eten!", "telefoon en zonnebril in tas houden bij apen"],
          tip: "Rustgevend bos met honderden makaak-apen. Geen eten meenemen. Zonnebril en telefoon in tas bij apen.",
          mapsUrl: "https://maps.google.com/?q=Ubud+Monkey+Forest",
        },
        {
          naam: "Tirta Empul Tempel",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "Rp 50.000",
          coordinaten: { lat: -8.4150, lng: 115.3117 },
          meenemen: ["sarong (huur ook ter plaatse)", "respectvolle kleding"],
          tip: "Heilig tempelcomplex met reinigingsritueel in heilig bronwater. Sarong verplicht. Respectvol gedragen.",
          mapsUrl: "https://maps.google.com/?q=Tirta+Empul+Temple+Bali",
        },
        {
          naam: "Balinese Kookworkshop ⚠️ Vooraf reserveren",
          categorie: "cultuur",
          duur: "4–5 uur",
          kosten: "~Rp 400.000 p.p.",
          coordinaten: { lat: -8.5069, lng: 115.2600 },
          meenemen: ["eetlust", "notitieblokje voor recepten"],
          tip: "Inclusief marktbezoek. Paon Bali of Casa Luna zijn topkeuzes. Minstens een dag van tevoren boeken.",
          mapsUrl: "https://maps.google.com/?q=Paon+Bali+Cooking+Class",
        },
      ],
      restaurants: [
        {
          naam: "Locavore",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Dewisita No.10, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Locavore+Ubud",
          reservering: true,
          openingstijden: "12:00–14:30 & 18:30–22:30 (di–zo)",
          tip: "Meerdere keren in de top 50 beste restaurants van Azië. Seizoensgebonden tasting menu. Weken vooruit boeken — absolute aanrader.",
        },
        {
          naam: "Naughty Nuri's",
          keuken: "BBQ ribben",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "15 min lopen",
          adres: "Jl. Raya Sanggingan No.135, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Naughty+Nuris+Ubud",
          reservering: false,
          openingstijden: "11:00–22:00",
          tip: "Legendarische spareribs en sterke martini's. Een Ubud-klassieker die je niet mag overslaan.",
        },
        {
          naam: "Room4Dessert",
          keuken: "Dessert tasting menu",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "20 min lopen",
          adres: "Jl. Sanggingan, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Room4Dessert+Ubud",
          reservering: true,
          openingstijden: "18:00–23:00",
          tip: "Van chef Will Goldfarb. Alleen desserts en cocktails. Verrassende, unieke ervaring.",
        },
        {
          naam: "Warung Babi Guling Ibu Oka",
          keuken: "Balinese BBQ",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Suweta No.2, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Ibu+Oka+Babi+Guling+Ubud",
          reservering: false,
          openingstijden: "11:00–15:00",
          tip: "Beroemde geroosterde biggetjes (babi guling). Anthony Bourdain at hier. Op = op, vroeg gaan.",
        },
        {
          naam: "Bridges Bali",
          keuken: "Modern Aziatisch / Fusion",
          sfeer: "romantisch",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "15 min lopen (Campuhan)",
          adres: "Jl. Raya Campuhan, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Bridges+Bali+Ubud",
          reservering: true,
          openingstijden: "11:00–23:00",
          tip: "Spectaculair gelegen boven de rivier. Geweldige sfeer voor een romantisch diner. Reserveer om een goede tafel te krijgen.",
        },
        {
          naam: "Clear Cafe",
          keuken: "Gezond / Vegan",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Jl. Hanoman No.8, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Clear+Cafe+Ubud",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Populair voor ontbijt en lunch. Biologisch, vegetarisch/vegan opties. Heerlijke smoothies en açaí bowls.",
        },
      ],
    },

    {
      id: "lembongan",
      stad: "Nusa Lembongan",
      land: "Bali",
      type: "strand",
      emoji: "🤿",
      coordinaten: { lat: -8.6801, lng: 115.4554 },
      datums: { aankomst: "2026-09-11", vertrek: "2026-09-15" },
      hotel: {
        naam: "Pemedal Beach Resort",
        adres: "Nusa Lembongan, Bali",
        mapsUrl: "https://maps.google.com/?q=Pemedal+Beach+Resort+Nusa+Lembongan",
        coordinaten: { lat: -8.6896, lng: 115.4378 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€66,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 10 september",
        opmerkingen: "✅ Al betaald.",
      },
      vervoer: {
        aankomst: {
          type: "ferry",
          van: "Ubud → Sanur Beach → Nusa Lembongan",
          opmerkingen: "Speedboot van Sanur Beach. ~30–45 min oversteek. ⚠️ Speedboot paar dagen van tevoren reserveren!",
        },
        vertrek: {
          type: "ferry",
          naar: "Bali (Sanur)",
          vertrekTijd: "2026-09-15T09:00:00",
          opmerkingen: "Speedboot terug naar Bali, daarna taxi naar Easy Surf Camp (~1,5 uur). ~3 uur totaal.",
        },
      },
      activiteiten: [
        {
          naam: "Snorkelen: Manta Point + Crystal Bay ⚠️ Vooraf boeken",
          categorie: "avontuur",
          duur: "hele dag",
          kosten: "~Rp 400.000 p.p.",
          coordinaten: { lat: -8.7358, lng: 115.4831 },
          meenemen: ["onderwatercamera of telefoonhoes", "reef-safe zonnebrandcrème", "zwemkleding", "handdoek", "zeeziektetablet (preventief)"],
          tip: "Combi-trip langs de mooiste snorkelplekken. Bij Manta Point grote kans op mantaroggen. Vooraf boeken via hotel of lokale aanbieder.",
          mapsUrl: "https://maps.google.com/?q=Manta+Point+Nusa+Penida",
        },
        {
          naam: "Blue Lagoon Uitkijkpunt",
          categorie: "natuur",
          duur: "2–3 uur",
          kosten: "gratis",
          coordinaten: { lat: -8.6944, lng: 115.4600 },
          meenemen: ["scooter huren (~Rp 70.000/dag)", "cash"],
          tip: "Prachtige kliffen en felturquoise water. Een van de mooiste uitzichtpunten van de eilandengroep. Te bereiken per scooter.",
          mapsUrl: "https://maps.google.com/?q=Blue+Lagoon+Nusa+Lembongan",
        },
        {
          naam: "Kajakken door mangrovebos (optioneel)",
          categorie: "avontuur",
          duur: "2 uur",
          kosten: "~Rp 150.000",
          coordinaten: { lat: -8.6830, lng: 115.4556 },
          tip: "Rustige kajaktocht door het mangrovebos. Boek via je hotel.",
          mapsUrl: "https://maps.google.com/?q=Mangrove+Forest+Nusa+Lembongan",
        },
        {
          naam: "Devil's Tear Kliffen",
          categorie: "natuur",
          duur: "1 uur",
          kosten: "gratis",
          coordinaten: { lat: -8.7033, lng: 115.4350 },
          tip: "Indrukwekkend klif waar golven met kracht op de rotsen slaan. Spectaculair bij opkomende vloed. Per scooter bereikbaar.",
          mapsUrl: "https://maps.google.com/?q=Devil%27s+Tear+Nusa+Lembongan",
        },
        {
          naam: "Scooter huren en eiland verkennen",
          categorie: "avontuur",
          duur: "hele dag",
          kosten: "~Rp 70.000/dag",
          coordinaten: { lat: -8.6901, lng: 115.4454 },
          tip: "Het eiland is klein en perfect per scooter te verkennen. Rijbewijs meenemen. Links rijden!",
          mapsUrl: "https://maps.google.com/?q=Nusa+Lembongan",
        },
      ],
      restaurants: [
        {
          naam: "Sandy Bay Beach Club",
          keuken: "Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "15 min lopen",
          adres: "Sandy Bay, Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Sandy+Bay+Beach+Club+Nusa+Lembongan",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Populairste beachclub van het eiland. Goed voor zonsondergang met cocktail.",
        },
        {
          naam: "Bali Eco Deli",
          keuken: "Gezond / Vegetarisch",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Bali+Eco+Deli+Nusa+Lembongan",
          reservering: false,
          openingstijden: "08:00–20:00",
          tip: "Frisse smoothiebowls en gezonde maaltijden. Goed na een dag snorkelen.",
        },
        {
          naam: "Warung lokaal (dorpje)",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "5 min lopen",
          adres: "Nusa Lembongan dorp",
          mapsUrl: "https://maps.google.com/?q=Nusa+Lembongan+village",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "Wandel door het dorp voor de goedkoopste en lekkerste lokale nasi goreng en mie goreng.",
        },
        {
          naam: "Hai Bar & Grill",
          keuken: "Grill / Beachclub",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          afstand: "10 min lopen",
          adres: "Mushroom Bay, Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Hai+Bar+Grill+Nusa+Lembongan",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Goed gegrild vlees en vis direct aan het water. Fantastisch voor een ontspannen avond. Uitzicht op de zonsondergang.",
        },
        {
          naam: "Pontoon Beach Club",
          keuken: "Internationaal",
          sfeer: "trendy",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "15 min lopen",
          adres: "Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Pontoon+Beach+Club+Nusa+Lembongan",
          reservering: false,
          openingstijden: "10:00–23:00",
          tip: "Populairste beach club van het eiland met zwembad en uitzicht op de zee. Goed voor een middag cocktails.",
        },
      ],
    },

    {
      id: "bali",
      stad: "Bali (Kuta)",
      land: "Bali",
      type: "strand",
      emoji: "🌴",
      coordinaten: { lat: -8.7183, lng: 115.1686 },
      datums: { aankomst: "2026-09-15", vertrek: "2026-09-17" },
      hotel: {
        naam: "Easy Surf Camp",
        adres: "Kuta, Bali (nabij vliegveld)",
        mapsUrl: "https://maps.google.com/?q=Easy+Surf+Camp+Kuta+Bali",
        coordinaten: { lat: -8.7218, lng: 115.1731 },
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Afschrijving 9 september",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€32,50",
        ontbijt: "niet inbegrepen",
        annulering: "vóór 12 september",
        opmerkingen: "Afschrijving 9 september. Nabij vliegveld — handig voor vroeg vertrek. ⚠️ Vlucht vertrekt 00:35 op 17 sep — vertrek hotel om ~22:00 op 16 sep.",
      },
      vervoer: {
        aankomst: {
          type: "ferry",
          van: "Nusa Lembongan → Bali (Sanur) → Kuta",
          opmerkingen: "Speedboot terug naar Bali, daarna taxi naar Kuta (~1,5 uur). ~3 uur totaal.",
        },
        vertrek: {
          type: "vlucht",
          naar: "Amsterdam AMS",
          vluchtnummer: "Vul vluchtnummer in",
          vertrekTijd: "2026-09-17T00:35:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "⚠️ Vertrek om 00:35 — midden in de nacht van 16 op 17 september! Vertrek hotel om ~22:00 op 16 september. Ngurah Rai Airport (DPS), ~15 min taxi.",
        },
      },
      activiteiten: [
        {
          naam: "Kuta Beach — Surfen",
          categorie: "avontuur",
          duur: "2–3 uur",
          kosten: "~Rp 200.000 incl. board",
          coordinaten: { lat: -8.7183, lng: 115.1686 },
          meenemen: ["zonnebrandcrème", "cash", "droge kleren"],
          tip: "Kuta is de perfecte plek voor beginners. Veel instructeurs op het strand. Surfboard huren kan ook zelfstandig.",
          mapsUrl: "https://maps.google.com/?q=Kuta+Beach+Bali",
        },
        {
          naam: "Tanah Lot Tempel bij Zonsondergang",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "Rp 60.000",
          coordinaten: { lat: -8.6209, lng: 115.0869 },
          meenemen: ["sarong (huur ook ter plaatse)", "camera"],
          tip: "Iconische zeerotstempel. ~30 min rijden. Ga voor zonsondergang (~17:30). Erg fotogeniek — perfecte laatste avond.",
          mapsUrl: "https://maps.google.com/?q=Tanah+Lot+Temple+Bali",
        },
        {
          naam: "Seminyak — Shoppen & Strandclubs",
          categorie: "winkelen",
          duur: "halve dag",
          kosten: "variabel",
          coordinaten: { lat: -8.6924, lng: 115.1624 },
          tip: "Loop van Kuta richting Seminyak voor betere winkels, restaurants en bars. Potato Head Beach Club is iconisch.",
          mapsUrl: "https://maps.google.com/?q=Seminyak+Bali",
        },
      ],
      restaurants: [
        {
          naam: "Merah Putih",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "25 min taxi (Seminyak)",
          adres: "Jl. Petitenget No.100X, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Merah+Putih+Seminyak",
          reservering: true,
          openingstijden: "12:00–23:00",
          tip: "Spectaculair bamboe interieur van 8 meter hoog. Indonesische gerechten met moderne twist. Perfect als afscheidsdiner.",
        },
        {
          naam: "La Lucciola",
          keuken: "Mediterraans",
          sfeer: "romantisch",
          prijsniveau: "€€€",
          michelin: 0,
          afstand: "30 min taxi (Seminyak)",
          adres: "Jl. Petitenget, Seminyak Beach, Bali",
          mapsUrl: "https://maps.google.com/?q=La+Lucciola+Seminyak",
          reservering: true,
          openingstijden: "11:00–23:00",
          tip: "Direct aan het strand. Perfect voor zonsondergang diner. Vraag om een tafel aan het raam.",
        },
        {
          naam: "Warung lokaal Kuta",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "5 min lopen",
          adres: "Kuta centrum",
          mapsUrl: "https://maps.google.com/?q=Kuta+Bali+centrum",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Laatste nasi goreng voor het vliegtuig. Kuta heeft veel goede lokale warungs in de zijstraten.",
        },
        {
          naam: "Sarong Restaurant",
          keuken: "Modern Aziatisch / Fine dining",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          afstand: "20 min taxi (Seminyak)",
          adres: "Jl. Petitenget No.19X, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Sarong+Restaurant+Seminyak",
          reservering: true,
          openingstijden: "18:30–23:00",
          tip: "Een van Bali's top fine dining restaurants. Prachtig interieur. Perfecte keuze voor een speciale laatste avond. Reserveer ver van tevoren.",
        },
        {
          naam: "Warung Made",
          keuken: "Balinese / Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          afstand: "5 min lopen (Kuta)",
          adres: "Jl. Pantai Kuta, Kuta, Bali",
          mapsUrl: "https://maps.google.com/?q=Warung+Made+Kuta+Bali",
          reservering: false,
          openingstijden: "08:00–23:00",
          tip: "Klassieke Kuta-warung met uitstekende nasi goreng en mie goreng. Al decennialang favoriet bij backpackers en surfers.",
        },
      ],
    },
  ],
};
