const REIS = {
  meta: {
    titel: "Indonesië 2026",
    reiziger: "Wouter & gezelschap",
    noodcontact: "+31 6 xx xxx xxx",
  },

  locaties: [
    {
      id: "jakarta",
      stad: "Jakarta",
      land: "Indonesië — Java",
      type: "stad",
      emoji: "🏙️",
      coordinaten: { lat: -6.2088, lng: 106.8456 },
      datums: {
        aankomst: "2026-08-23",
        vertrek: "2026-08-25",
      },
      hotel: {
        naam: "Jambuluwuk Thamrin Hotel",
        adres: "Jl. M.H. Thamrin, Jakarta Pusat",
        mapsUrl: "https://maps.google.com/?q=Jambuluwuk+Thamrin+Hotel+Jakarta",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€55",
        ontbijt: "inbegrepen",
        annulering: "vóór 18 augustus",
        opmerkingen: "✅ Al betaald. Aankomst ~14:50 plaatselijke tijd. Taxi vanaf vliegveld ~30 min.",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Amsterdam AMS",
          vluchtnummer: "Vul vluchtnummer in",
          aankomstTijd: "2026-08-23T14:50:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "Soekarno-Hatta Airport (CGK). Bluebird taxi naar hotel ~30 min, ~Rp 150.000. Geen onofficiële taxichauffeurs meegaan.",
        },
        vertrek: {
          type: "trein",
          naar: "Yogyakarta",
          vertrekTijd: "2026-08-25T08:00:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "~6,5 uur treinreis. Tickets via astrindotour.co.id. Vertrekstation: Jakarta Gambir.",
        },
      },
      activiteiten: [
        {
          naam: "Kota Tua — Fatahillah Square",
          categorie: "bezienswaardigheden",
          duur: "2–3 uur",
          kosten: "gratis",
          tip: "Het koloniale hart van Jakarta. Centraal plein vol straatleven. Bezoek Café Batavia (iconisch koloniaal café uit 1805) en Museum Bank Indonesia (modern museum over handel en de VOC).",
          mapsUrl: "https://maps.google.com/?q=Fatahillah+Square+Jakarta",
        },
        {
          naam: "Istiqlal Moskee + Jakarta Cathedral",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "gratis",
          tip: "Grootste moskee van Zuidoost-Azië recht tegenover een katholieke kathedraal — symbool voor religieuze tolerantie. Schouders en knieën bedekken. Soms gratis gids.",
          mapsUrl: "https://maps.google.com/?q=Istiqlal+Mosque+Jakarta",
        },
        {
          naam: "Glodok (Chinese wijk)",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "gratis",
          tip: "Oudste Chinese wijk van Jakarta. Levendig en chaotisch met Chinese tempels en avondmarktjes. Wordt het levendigst vanaf 17:00.",
          mapsUrl: "https://maps.google.com/?q=Glodok+Jakarta",
        },
        {
          naam: "Henshin Rooftop Bar",
          categorie: "bezienswaardigheden",
          duur: "2 uur",
          kosten: "€€€€",
          tip: "Luxe rooftop bar met spectaculair panorama over de skyline. Perfect voor de avond. Eventueel vooraf reserveren.",
          mapsUrl: "https://maps.google.com/?q=Henshin+Bar+Jakarta",
        },
      ],
      restaurants: [
        {
          naam: "Namaaz Dining",
          keuken: "Indonesisch moleculair",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          adres: "Jl. Sriwijaya I No.40, Kebayoran Baru, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Namaaz+Dining+Jakarta",
          reservering: true,
          openingstijden: "18:30–23:00 (di–za)",
          tip: "Indonesische moleculaire gastronomie op topniveau. 16 verrassingsgerechten. Weken van tevoren reserveren — absoluut bijzonder.",
        },
        {
          naam: "Sate Khas Senayan",
          keuken: "Indonesisch",
          sfeer: "authentiek",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Kebon Sirih No.31A, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Sate+Khas+Senayan+Jakarta",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Beste sate van Jakarta. Bestel de sate kambing (geit). Contant betalen.",
        },
        {
          naam: "Café Batavia",
          keuken: "Internationaal / Koloniaal",
          sfeer: "historisch",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Pintu Besar Utara No.14, Kota Tua",
          mapsUrl: "https://maps.google.com/?q=Cafe+Batavia+Jakarta",
          reservering: false,
          openingstijden: "09:00–24:00",
          tip: "Iconisch koloniaal pand uit 1805 op Fatahillah Square. Goed voor lunch na Kota Tua.",
        },
        {
          naam: "Warung Nasi Ampera",
          keuken: "Sundanees",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Meerdere locaties in Jakarta",
          mapsUrl: "https://maps.google.com/?q=Warung+Nasi+Ampera+Jakarta",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Authentiek Sundanees eten. Wijs gewoon aan wat je wilt. Lokale favoriet, spotgoedkoop.",
        },
      ],
    },

    {
      id: "yogyakarta",
      stad: "Yogyakarta",
      land: "Indonesië — Java",
      type: "cultuur",
      emoji: "🏯",
      coordinaten: { lat: -7.7956, lng: 110.3695 },
      datums: {
        aankomst: "2026-08-25",
        vertrek: "2026-08-29",
      },
      hotel: {
        naam: "Melia Purosani Yogyakarta",
        adres: "Jl. Suryotomo No.31, Yogyakarta",
        mapsUrl: "https://maps.google.com/?q=Melia+Purosani+Yogyakarta",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€75,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 23 augustus",
        opmerkingen: "✅ Al betaald. Centraal gelegen, loopafstand tot Malioboro Street en Kraton.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Jakarta Gambir",
          opmerkingen: "~6,5 uur treinreis. Aankomst station Yogyakarta (Tugu). Taxi naar hotel ~10 min.",
        },
        vertrek: {
          type: "vlucht",
          naar: "Surabaya → Malang",
          vertrekTijd: "2026-08-29T07:00:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "Reisdag! Vliegtuig Yogyakarta → Surabaya, daarna trein naar Malang (~1:15 uur). Hele dag onderweg.",
        },
      },
      activiteiten: [
        {
          naam: "Borobudur Tempel ⚠️ Ticket vooraf kopen!",
          categorie: "cultuur",
          duur: "halve dag",
          kosten: "Rp 350.000",
          tip: "Grootste boeddhistische monument ter wereld. Ga bij zonsopgang. BELANGRIJK: 'Structure temple climb ticket' vooraf online kopen — ter plaatse niet altijd beschikbaar. ~1 uur rijden.",
          mapsUrl: "https://maps.google.com/?q=Borobudur+Temple",
        },
        {
          naam: "Prambanan Tempelcomplex ⚠️ Ticket vooraf kopen!",
          categorie: "cultuur",
          duur: "halve dag",
          kosten: "Rp 350.000",
          tip: "Indrukwekkend Hindoe-tempelcomplex (in 2006 nog door aardbeving getroffen). Slim om vooraf ticket te boeken. Ga vanaf 15:30 tot zonsondergang voor het mooiste licht. Bezoek ook Sewu Temple op loopafstand. ~30 min rijden.",
          mapsUrl: "https://maps.google.com/?q=Prambanan+Temple",
        },
        {
          naam: "Jomblang Cave (optioneel) ⚠️ Vooraf boeken",
          categorie: "avontuur",
          duur: "halve dag",
          kosten: "~Rp 450.000",
          tip: "Spectaculaire touwafdaling in een grot met een lichtstraal van boven ('heaven's light'). Vooraf boeken want beperkt aantal plekken per dag.",
          mapsUrl: "https://maps.google.com/?q=Jomblang+Cave+Yogyakarta",
        },
        {
          naam: "Mount Merapi Vulkaan",
          categorie: "avontuur",
          duur: "halve dag",
          kosten: "~Rp 400.000 p.p.",
          tip: "Actieve vulkaan die in 2024 nog uitbarstte. Jeep-tour over lavastromen. Spectaculair. Boek via hotel.",
          mapsUrl: "https://maps.google.com/?q=Mount+Merapi+Yogyakarta",
        },
        {
          naam: "Malioboro Street",
          categorie: "winkelen",
          duur: "2 uur",
          kosten: "variabel",
          tip: "Bekendste straat van Yogya. Chaotisch en leuk, veel marktjes en straatmuzikanten. In de avond het leukst. Let op zakkenrollers.",
          mapsUrl: "https://maps.google.com/?q=Jalan+Malioboro+Yogyakarta",
        },
        {
          naam: "Prawirotaman (wijk)",
          categorie: "bezienswaardigheden",
          duur: "vrij",
          kosten: "variabel",
          tip: "Relaxte wijk vol cafés, massagesalons en restaurants. Goed voor een rustige avond.",
          mapsUrl: "https://maps.google.com/?q=Prawirotaman+Yogyakarta",
        },
      ],
      restaurants: [
        {
          naam: "Restaurant Mediterranea By Kamil",
          keuken: "Mediterraans / Fusion",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Restaurant+Mediterranea+By+Kamil+Yogyakarta",
          reservering: true,
          openingstijden: "18:00–22:00",
          tip: "Overal terugkomend als toprestaurant in Yogya. ⚠️ Reserveren vanaf 2 maanden van tevoren — zo snel mogelijk boeken!",
        },
        {
          naam: "Bale Raos",
          keuken: "Javaans Paleis",
          sfeer: "authentiek",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Magangan Kulon No.1, Kraton, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Bale+Raos+Yogyakarta",
          reservering: true,
          openingstijden: "11:00–21:00",
          tip: "Gerechten uit de eeuwenoude sultanskeukens van het Kraton. Unieke, authentieke ervaring.",
        },
        {
          naam: "Gudeg Yu Djum",
          keuken: "Javaans",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Jl. Kaliurang KM 4.5, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Gudeg+Yu+Djum+Yogyakarta",
          reservering: false,
          openingstijden: "06:00–14:00",
          tip: "Beste gudeg (gestoofde jackfruit) van Yogya. Legendarisch. Kom vroeg want op = op.",
        },
        {
          naam: "Via Via Restaurant",
          keuken: "Indonesisch / Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Prawirotaman I No.30, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Via+Via+Restaurant+Yogyakarta",
          reservering: false,
          openingstijden: "08:00–23:00",
          tip: "Gezellig terras in Prawirotaman. Goede cocktails. Culturele optredens in de avond.",
        },
      ],
    },

    {
      id: "malang",
      stad: "Malang",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "💧",
      coordinaten: { lat: -7.9839, lng: 112.6214 },
      datums: {
        aankomst: "2026-08-29",
        vertrek: "2026-09-01",
      },
      hotel: {
        naam: "Snooze Hostel Malang",
        adres: "Malang, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Snooze+Hostel+Malang",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "⚠️ Betalen vóór 23 augustus!",
        bron: "booking.com",
        nachten: 3,
        prijsPerNacht: "€31,66",
        ontbijt: "niet inbegrepen",
        annulering: "vóór 26 augustus",
        opmerkingen: "⚠️ Nog betalen vóór 23 augustus!",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Yogyakarta → Surabaya (vlucht) → Malang (trein)",
          opmerkingen: "Reisdag. Vliegtuig Yogyakarta → Surabaya, daarna trein Surabaya → Malang (~1:15 uur). Taxi vanuit station naar hotel.",
        },
        vertrek: {
          type: "trein",
          naar: "Probolinggo",
          opmerkingen: "~2,5 uur met de trein. Aankomst Probolinggo, taxi naar Bromo Park Hotel.",
        },
      },
      activiteiten: [
        {
          naam: "Tumpak Sewu Waterval ⚠️ Vervoer vooraf regelen",
          categorie: "natuur",
          duur: "hele dag",
          kosten: "~Rp 150.000 + chauffeur",
          tip: "Mooiste waterval van Indonesië (sommigen zeggen van Azië). Waterschoenen mee! Regel een privéchauffeur of tour via het hostel + park tickets vooraf kopen. ~3 uur rijden.",
          mapsUrl: "https://maps.google.com/?q=Tumpak+Sewu+Waterfall",
        },
        {
          naam: "Kajoetangan Heritage Village",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "gratis",
          tip: "Historische wijk met gerestaureerde koloniale straatjes, kleine steegjes en oude huizen. Goed voor foto's.",
          mapsUrl: "https://maps.google.com/?q=Kajoetangan+Heritage+Village+Malang",
        },
        {
          naam: "Idjen Boulevard",
          categorie: "bezienswaardigheden",
          duur: "1 uur",
          kosten: "gratis",
          tip: "Brede koloniale boulevard met oude villa's uit de Nederlandse tijd.",
          mapsUrl: "https://maps.google.com/?q=Ijen+Boulevard+Malang",
        },
        {
          naam: "Kampung Warna Warni Jodipan",
          categorie: "bezienswaardigheden",
          duur: "1 uur",
          kosten: "Rp 5.000",
          tip: "Kleurrijke regenboogwijk — arme wijk met vrolijke beschilderingen. Goed voor foto's.",
          mapsUrl: "https://maps.google.com/?q=Kampung+Warna+Warni+Jodipan+Malang",
        },
      ],
      restaurants: [
        {
          naam: "Warung Daging Sapi Malang",
          keuken: "Javaans / Lokaal",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Malang centrum",
          mapsUrl: "https://maps.google.com/?q=warung+malang+centrum",
          reservering: false,
          openingstijden: "08:00–20:00",
          tip: "Malang staat bekend om zijn bakso (gehaktballensoep). Volg de locals naar de beste warung.",
        },
        {
          naam: "Toko Oen",
          keuken: "Koloniale ijssalon",
          sfeer: "historisch",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Jend. Basuki Rachmat No.5, Malang",
          mapsUrl: "https://maps.google.com/?q=Toko+Oen+Malang",
          reservering: false,
          openingstijden: "09:00–21:00",
          tip: "Iconische koloniale ijssalon uit 1930. Beroemd om ijs en Nederlandse gebakjes. Een stukje geschiedenis.",
        },
      ],
    },

    {
      id: "bromo",
      stad: "Probolinggo (Bromo)",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "🌋",
      coordinaten: { lat: -7.9425, lng: 112.9530 },
      datums: {
        aankomst: "2026-09-01",
        vertrek: "2026-09-03",
      },
      hotel: {
        naam: "Bromo Park Hotel",
        adres: "Probolinggo, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Bromo+Park+Hotel+Probolinggo",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Afschrijving 22 september",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€67",
        ontbijt: "inbegrepen",
        annulering: "vóór 24 augustus",
        opmerkingen: "Afschrijving vindt automatisch plaats op 22 september.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Malang",
          opmerkingen: "~2,5 uur trein. Taxi vanuit Probolinggo station naar hotel.",
        },
        vertrek: {
          type: "trein",
          naar: "Licin (via Banyuwangi)",
          opmerkingen: "~5 uur met trein en taxi. Trein naar Banyuwangi, taxi naar Licin.",
        },
      },
      activiteiten: [
        {
          naam: "Mount Bromo bij Zonsopgang",
          categorie: "natuur",
          duur: "hele ochtend",
          kosten: "Rp 220.000 (park) + jeep ~Rp 300.000",
          tip: "Actieve vulkaan — barstte in 2019 nog uit. Vertrek om ~02:00 voor zonsopgang op het uitkijkpunt. Jeep regelen via hotel. ~1,5 uur rijden. Neem warme kleding mee — het is koud op 2.329m.",
          mapsUrl: "https://maps.google.com/?q=Mount+Bromo+East+Java",
        },
        {
          naam: "Bromo Tengger Semeru Nationaal Park",
          categorie: "natuur",
          duur: "halve dag",
          kosten: "Rp 220.000",
          tip: "Wandeling van ~6 km (3 uur) vanuit Cemoro Lawang naar de kraterrand. Eventueel omweg via Madakaripura Waterval (omweg waard!).",
          mapsUrl: "https://maps.google.com/?q=Bromo+Tengger+Semeru+National+Park",
        },
      ],
      restaurants: [
        {
          naam: "Café Lava Bromo",
          keuken: "Indonesisch / Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Cemoro Lawang, nabij Bromo",
          mapsUrl: "https://maps.google.com/?q=Cafe+Lava+Bromo",
          reservering: false,
          openingstijden: "06:00–21:00",
          tip: "Populair bij vulkaanbezoekers. Goed voor een warme kop koffie na de vroege ochtend op de vulkaan.",
        },
      ],
    },

    {
      id: "ijen",
      stad: "Licin (Ijen)",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "🔥",
      coordinaten: { lat: -8.0631, lng: 114.2333 },
      datums: {
        aankomst: "2026-09-03",
        vertrek: "2026-09-05",
      },
      hotel: {
        naam: "Lintang Luku Tent Resort",
        adres: "Licin, nabij Banyuwangi, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Lintang+Luku+tent+resort+Licin",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€82",
        ontbijt: "inbegrepen",
        annulering: "NIET annuleerbaar",
        opmerkingen: "✅ Al betaald. ⚠️ Kan niet meer geannuleerd worden.",
      },
      vervoer: {
        aankomst: {
          type: "trein",
          van: "Probolinggo → Banyuwangi (trein) → Licin (taxi)",
          opmerkingen: "~5 uur. Trein naar Banyuwangi, daarna taxi naar Licin (~30 min). Taxi vooraf regelen.",
        },
        vertrek: {
          type: "auto",
          naar: "Kalibaru",
          opmerkingen: "~2 uur rijden naar Kalibaru. Taxi of private driver regelen.",
        },
      },
      activiteiten: [
        {
          naam: "Kawah Ijen (Blue Fire)",
          categorie: "natuur",
          duur: "hele nacht + ochtend",
          kosten: "Rp 150.000 + gids aanbevolen",
          tip: "Een van de meest indrukwekkende ervaringen van Indonesië. Het 'blue fire' is alleen bij nacht te zien (door gaslekkage). Vertrek ~23:00, wandeling 3 km omhoog (~1,5 uur). Gasmasker verplicht (te huur). Neem warme kleding mee.",
          mapsUrl: "https://maps.google.com/?q=Kawah+Ijen+Banyuwangi",
        },
        {
          naam: "Ijen Turquoise Kratermeer",
          categorie: "natuur",
          duur: "bij zonsopgang",
          kosten: "inbegrepen bij Ijen ticket",
          tip: "Na het zien van de blue fire kun je bij zonsopgang het grootste zure kratermeer ter wereld zien (turquoise kleur). Indrukwekkend uitzicht.",
          mapsUrl: "https://maps.google.com/?q=Ijen+Crater+Lake",
        },
      ],
      restaurants: [
        {
          naam: "Eethuis bij het resort",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Licin, Banyuwangi",
          mapsUrl: "https://maps.google.com/?q=Licin+Banyuwangi",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "In Licin zijn weinig opties. Het ontbijt bij het tent resort is inbegrepen. Neem wat snacks mee voor de Ijen-tocht.",
        },
      ],
    },

    {
      id: "kalibaru",
      stad: "Kalibaru",
      land: "Indonesië — Oost-Java",
      type: "natuur",
      emoji: "☕",
      coordinaten: { lat: -8.2467, lng: 114.0867 },
      datums: {
        aankomst: "2026-09-05",
        vertrek: "2026-09-07",
      },
      hotel: {
        naam: "Villa Kendi",
        adres: "Kalibaru, Banyuwangi, Oost-Java",
        mapsUrl: "https://maps.google.com/?q=Villa+Kendi+Kalibaru",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€27",
        ontbijt: "inbegrepen",
        annulering: "vóór 2 september",
        opmerkingen: "✅ Al betaald. ⚠️ BELANGRIJK: vervoer naar het hotel VAN TEVOREN aanvragen bij het hotel zelf — het is moeilijk bereikbaar!",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Licin",
          opmerkingen: "~2 uur rijden. ⚠️ Vervoer naar het hotel vooraf aanvragen bij Villa Kendi — hotel is moeilijk te bereiken zonder eigen vervoer.",
        },
        vertrek: {
          type: "auto",
          naar: "Ubud (Bali)",
          opmerkingen: "Hele dag onderweg. Auto naar Ketapang haven → ferry naar Gilimanuk (Bali) → auto naar Ubud (~3,5 uur).",
        },
      },
      activiteiten: [
        {
          naam: "Koffieplantage rondleiding",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "variabel",
          tip: "Kalibaru staat bekend om zijn koffieplantages. Vraag het hotel om een rondleiding te regelen. Je ziet hoe koffie, vanille en cacao worden verbouwd.",
          mapsUrl: "https://maps.google.com/?q=Coffee+Plantation+Kalibaru",
        },
        {
          naam: "Natuur & rust",
          categorie: "natuur",
          duur: "vrij",
          kosten: "gratis",
          tip: "Na de intensieve Bromo en Ijen tochten is dit een ideale rustdag. Genieten van het groene landschap en de frisse berglucht.",
          mapsUrl: "https://maps.google.com/?q=Kalibaru+East+Java",
        },
      ],
      restaurants: [
        {
          naam: "Eethuis bij Villa Kendi",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Kalibaru, Oost-Java",
          mapsUrl: "https://maps.google.com/?q=Villa+Kendi+Kalibaru",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "In Kalibaru zijn weinig restaurants. Ontbijt is inbegrepen bij het hotel. Vraag het hotel om lokale eetgelegenheden aan te bevelen.",
        },
      ],
    },

    {
      id: "ubud",
      stad: "Ubud",
      land: "Bali",
      type: "natuur",
      emoji: "🌿",
      coordinaten: { lat: -8.5069, lng: 115.2625 },
      datums: {
        aankomst: "2026-09-07",
        vertrek: "2026-09-11",
      },
      hotel: {
        naam: "Alamdini Resort Ubud",
        adres: "Ubud, Bali",
        mapsUrl: "https://maps.google.com/?q=Alamdini+Resort+Ubud",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "11:00",
        boekingsnummer: "Betalen bij accommodatie",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€46,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 5 september",
        opmerkingen: "Betaling bij aankomst. Cancel vóór 5 september.",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Kalibaru → ferry → Bali → Ubud",
          opmerkingen: "Hele reisdag. Auto naar Ketapang haven, ferry naar Gilimanuk (Bali), auto naar Ubud (~3,5 uur). Ferry is kort (~45 min).",
        },
        vertrek: {
          type: "ferry",
          naar: "Nusa Lembongan",
          vertrekTijd: "2026-09-11T09:00:00",
          opmerkingen: "~3 uur boot + taxi. Speedboot van Sanur Beach of Padang Bai naar Nusa Lembongan. ⚠️ Speedboot paar dagen van tevoren reserveren!",
        },
      },
      activiteiten: [
        {
          naam: "Sidemen (dagtrip, 8 sep)",
          categorie: "natuur",
          duur: "hele dag",
          kosten: "Rp 50.000 + auto",
          tip: "Rustig dal met de mooiste rijstterrassen van Bali (mooier en rustiger dan Tegallalang). ~1,5 uur rijden. Wandeling door de velden aanbevolen.",
          mapsUrl: "https://maps.google.com/?q=Sidemen+Bali",
        },
        {
          naam: "Tegallalang Rijstterrassen (9 sep)",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "~Rp 15.000",
          tip: "Bekendste uitzicht van Bali. Ga vroeg (07:00) voor de drukte. Neem cash mee voor lokale bijdragen.",
          mapsUrl: "https://maps.google.com/?q=Tegallalang+Rice+Terrace",
        },
        {
          naam: "Kanto Lampo Waterval (10 sep)",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          tip: "Bekend om het water dat trapgewijs over de rotsen stroomt. Waterschoenen mee! Prachtig voor foto's.",
          mapsUrl: "https://maps.google.com/?q=Kanto+Lampo+Waterfall+Bali",
        },
        {
          naam: "Campuhan Ridge Walk",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "gratis",
          tip: "Wandeling van 2 km over heuvelrug met uitzicht op groene valleien. Vertrek bij zonsopgang.",
          mapsUrl: "https://maps.google.com/?q=Campuhan+Ridge+Walk+Ubud",
        },
        {
          naam: "Tibumana Waterval",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          tip: "Mooiste en relatief rustige waterval van Ubud-gebied.",
          mapsUrl: "https://maps.google.com/?q=Tibumana+Waterfall+Bali",
        },
        {
          naam: "Balinese Kookworkshop (optioneel) ⚠️ Vooraf reserveren",
          categorie: "cultuur",
          duur: "4–5 uur",
          kosten: "~Rp 400.000 p.p.",
          tip: "Inclusief marktbezoek. Paon Bali of Casa Luna zijn topkeuzes. Vooraf reserveren.",
          mapsUrl: "https://maps.google.com/?q=Paon+Bali+Cooking+Class",
        },
        {
          naam: "Maya Ubud Spa (optioneel) ⚠️ Vooraf reserveren",
          categorie: "bezienswaardigheden",
          duur: "2–4 uur",
          kosten: "€€€",
          tip: "Maya Ubud Spa & Pool — luxe wellnessbehandeling midden in de jungle. Vooraf reserveren.",
          mapsUrl: "https://maps.google.com/?q=Maya+Ubud+Resort+Spa",
        },
      ],
      restaurants: [
        {
          naam: "Locavore",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          adres: "Jl. Dewisita No.10, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Locavore+Ubud",
          reservering: true,
          openingstijden: "12:00–14:30 & 18:30–22:30 (di–zo)",
          tip: "Meerdere keren in de top 50 beste restaurants van Azië. Seizoensgebonden tasting menu. Weken vooruit boeken — absolute aanrader.",
        },
        {
          naam: "Room4Dessert",
          keuken: "Dessert tasting menu",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Sanggingan, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Room4Dessert+Ubud",
          reservering: true,
          openingstijden: "18:00–23:00",
          tip: "Van chef Will Goldfarb. Alleen desserts en cocktails. Verrassende, unieke ervaring.",
        },
        {
          naam: "Warung Babi Guling Ibu Oka",
          keuken: "Balinese BBQ",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Jl. Suweta No.2, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Ibu+Oka+Babi+Guling+Ubud",
          reservering: false,
          openingstijden: "11:00–15:00",
          tip: "Beroemde geroosterde biggetjes (babi guling). Anthony Bourdain at hier. Op = op, vroeg gaan.",
        },
        {
          naam: "Naughty Nuri's",
          keuken: "BBQ ribben",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Raya Sanggingan No.135, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Naughty+Nuris+Ubud",
          reservering: false,
          openingstijden: "11:00–22:00",
          tip: "Legendarische spareribs en sterke martini's. Een Ubud-klassieker.",
        },
      ],
    },

    {
      id: "lembongan",
      stad: "Nusa Lembongan",
      land: "Bali",
      type: "strand",
      emoji: "🤿",
      coordinaten: { lat: -8.6801, lng: 115.4554 },
      datums: {
        aankomst: "2026-09-11",
        vertrek: "2026-09-15",
      },
      hotel: {
        naam: "Pemedal Beach Resort",
        adres: "Nusa Lembongan, Bali",
        mapsUrl: "https://maps.google.com/?q=Pemedal+Beach+Resort+Nusa+Lembongan",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Al betaald",
        bron: "booking.com",
        nachten: 4,
        prijsPerNacht: "€66,50",
        ontbijt: "inbegrepen",
        annulering: "vóór 10 september",
        opmerkingen: "✅ Al betaald.",
      },
      vervoer: {
        aankomst: {
          type: "ferry",
          van: "Ubud → Sanur Beach (Bali) → Nusa Lembongan",
          opmerkingen: "Speedboot van Sanur Beach of Padang Bai. ~30–45 min oversteek. ⚠️ Speedboot een paar dagen van tevoren reserveren!",
        },
        vertrek: {
          type: "ferry",
          naar: "Bali (Sanur/Padang Bai)",
          vertrekTijd: "2026-09-15T09:00:00",
          opmerkingen: "Speedboot terug naar Bali, daarna taxi naar Easy Surf Camp (~1,5 uur). ~3 uur totaal.",
        },
      },
      activiteiten: [
        {
          naam: "Snorkelen: Manta Point + Crystal Bay + Mangrove Point ⚠️ Vooraf boeken",
          categorie: "avontuur",
          duur: "hele dag",
          kosten: "~Rp 400.000 p.p.",
          tip: "Combi-trip langs de drie mooiste snorkelplekken. Bij Manta Point kans op mantaroggen. Vooraf boeken via hotel of lokale aanbieder.",
          mapsUrl: "https://maps.google.com/?q=Manta+Point+Nusa+Penida",
        },
        {
          naam: "Blue Lagoon",
          categorie: "natuur",
          duur: "2–3 uur",
          kosten: "gratis",
          tip: "Prachtige kliffen en felturquoise water — een van de mooiste uitzichtpunten van de eilandengroep. Te bereiken per scooter.",
          mapsUrl: "https://maps.google.com/?q=Blue+Lagoon+Nusa+Lembongan",
        },
        {
          naam: "Kajakken door mangrovebos (optioneel)",
          categorie: "avontuur",
          duur: "2 uur",
          kosten: "~Rp 150.000",
          tip: "Rustige kajaktocht door het mangrovebos. Boek via je hotel.",
          mapsUrl: "https://maps.google.com/?q=Mangrove+Forest+Nusa+Lembongan",
        },
        {
          naam: "Strand & vrije tijd",
          categorie: "natuur",
          duur: "vrij",
          kosten: "gratis",
          tip: "Nusa Lembongan is relatief rustig en authentiek vergeleken met het Bali-vasteland. Geniet van de stranden en de relaxte sfeer.",
          mapsUrl: "https://maps.google.com/?q=Nusa+Lembongan+Beach",
        },
      ],
      restaurants: [
        {
          naam: "Sandy Bay Beach Club",
          keuken: "Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Sandy Bay, Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Sandy+Bay+Beach+Club+Nusa+Lembongan",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Populairste beachclub van het eiland. Goed voor zonsondergang met cocktail.",
        },
        {
          naam: "Bali Eco Deli",
          keuken: "Gezond / Vegetarisch",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Nusa Lembongan",
          mapsUrl: "https://maps.google.com/?q=Bali+Eco+Deli+Nusa+Lembongan",
          reservering: false,
          openingstijden: "08:00–20:00",
          tip: "Frisse smoothiebowls en gezonde maaltijden. Goed na een dag snorkelen.",
        },
        {
          naam: "Warung lokaal",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Nusa Lembongan dorp",
          mapsUrl: "https://maps.google.com/?q=Nusa+Lembongan+village",
          reservering: false,
          openingstijden: "07:00–21:00",
          tip: "Wandel door het dorp voor de goedkoopste en lekkerste lokale nasi goreng en mie goreng.",
        },
      ],
    },

    {
      id: "bali",
      stad: "Bali (Kuta)",
      land: "Bali",
      type: "strand",
      emoji: "🌴",
      coordinaten: { lat: -8.7183, lng: 115.1686 },
      datums: {
        aankomst: "2026-09-15",
        vertrek: "2026-09-17",
      },
      hotel: {
        naam: "Easy Surf Camp",
        adres: "Kuta, Bali (nabij vliegveld)",
        mapsUrl: "https://maps.google.com/?q=Easy+Surf+Camp+Kuta+Bali",
        telefoon: "",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "Afschrijving 9 september",
        bron: "booking.com",
        nachten: 2,
        prijsPerNacht: "€32,50",
        ontbijt: "niet inbegrepen",
        annulering: "vóór 12 september",
        opmerkingen: "Afschrijving 9 september. Nabij vliegveld — handig voor vroeg vertrek.",
      },
      vervoer: {
        aankomst: {
          type: "ferry",
          van: "Nusa Lembongan → Bali (Sanur) → Kuta",
          opmerkingen: "Speedboot terug naar Bali, daarna taxi naar Kuta (~1,5 uur). ~3 uur totaal.",
        },
        vertrek: {
          type: "vlucht",
          naar: "Amsterdam AMS",
          vluchtnummer: "Vul vluchtnummer in",
          vertrekTijd: "2026-09-17T00:35:00",
          boekingsnummer: "Vul referentie in",
          opmerkingen: "⚠️ Vertrek om 00:35 — dit is midden in de nacht! Vertrek hotel om ~22:00 op 16 september. Ngurah Rai Airport (DPS), ~15 min taxi.",
        },
      },
      activiteiten: [
        {
          naam: "Kuta Beach — Surfen",
          categorie: "avontuur",
          duur: "2–3 uur",
          kosten: "~Rp 200.000 incl. board",
          tip: "Kuta is de perfecte plek voor beginners. Veel instructeurs op het strand. Surfboard huren kan ook zelfstandig.",
          mapsUrl: "https://maps.google.com/?q=Kuta+Beach+Bali",
        },
        {
          naam: "Seminyak / Legian — Shoppen en eten",
          categorie: "winkelen",
          duur: "halve dag",
          kosten: "variabel",
          tip: "Loop van Kuta richting Seminyak voor betere winkels, restaurants en bars. Onderhandel op de markt.",
          mapsUrl: "https://maps.google.com/?q=Seminyak+Bali",
        },
        {
          naam: "Zonsondergang Tanah Lot Tempel",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "Rp 60.000",
          tip: "Iconische zeerotstempel bij zonsondergang. ~30 min rijden. Erg fotogeniek — ideale laatste avond.",
          mapsUrl: "https://maps.google.com/?q=Tanah+Lot+Temple+Bali",
        },
      ],
      restaurants: [
        {
          naam: "Merah Putih",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Petitenget No.100X, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Merah+Putih+Seminyak",
          reservering: true,
          openingstijden: "12:00–23:00",
          tip: "Spectaculair bamboe interieur van 8 meter hoog. Indonesische gerechten met moderne twist. Perfect als afscheidsdiner.",
        },
        {
          naam: "La Lucciola",
          keuken: "Mediterraans",
          sfeer: "romantisch",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Petitenget, Seminyak Beach, Bali",
          mapsUrl: "https://maps.google.com/?q=La+Lucciola+Seminyak",
          reservering: true,
          openingstijden: "11:00–23:00",
          tip: "Direct aan het strand. Perfect voor laatste zonsondergang diner. Vraag om een tafel aan het raam.",
        },
        {
          naam: "Warung lokaal Kuta",
          keuken: "Indonesisch",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Kuta centrum",
          mapsUrl: "https://maps.google.com/?q=Kuta+Bali+centrum",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Laatste nasi goreng voor het vliegtuig. Kuta heeft veel goede lokale warungs in de zijstraten.",
        },
      ],
    },
  ],
};
