const REIS = {
  meta: {
    titel: "Indonesië 2026",
    reiziger: "Wouter & gezelschap",
    noodcontact: "+31 6 xx xxx xxx",
  },

  locaties: [
    {
      id: "jakarta",
      stad: "Jakarta",
      land: "Indonesië",
      type: "stad",
      emoji: "🏙️",
      datums: {
        aankomst: "2026-07-15",
        vertrek: "2026-07-17",
      },
      hotel: {
        naam: "Vul je hotel in",
        adres: "Vul het adres in, Jakarta",
        mapsUrl: "https://maps.google.com/?q=Jakarta",
        telefoon: "+62 21 xxx xxxx",
        checkIn: "15:00",
        checkOut: "12:00",
        boekingsnummer: "VUL-IN",
        bron: "booking.com",
        nachten: 2,
        opmerkingen: "Vul je eigen boekingsnummer in",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Amsterdam AMS",
          vluchtnummer: "VLUCHT-NR",
          terminal: "3",
          aankomstTijd: "2026-07-15T06:00:00",
          boekingsnummer: "VLUCHT-REF",
          opmerkingen: "Soekarno-Hatta International Airport (CGK)",
        },
        vertrek: {
          type: "vlucht",
          naar: "Yogyakarta JOG",
          vluchtnummer: "VLUCHT-NR",
          vertrekTijd: "2026-07-17T09:00:00",
          boekingsnummer: "VLUCHT-REF",
          opmerkingen: "Vertrek vanuit Terminal 3",
        },
      },
      activiteiten: [
        {
          naam: "Kota Tua (Oud Stadscentrum)",
          categorie: "bezienswaardigheden",
          duur: "2–3 uur",
          kosten: "gratis",
          tip: "Ga vroeg voor de hitte. Bezoek het Wayang Museum en drink koffie bij Café Batavia op het plein.",
          mapsUrl: "https://maps.google.com/?q=Kota+Tua+Jakarta",
        },
        {
          naam: "National Museum (Museum Nasional)",
          categorie: "cultuur",
          duur: "2 uur",
          kosten: "Rp 15.000",
          tip: "Gesloten op maandag. Goede introductie tot Indonesische geschiedenis en cultuur.",
          mapsUrl: "https://maps.google.com/?q=Museum+Nasional+Indonesia",
        },
        {
          naam: "Monas (Nationaal Monument)",
          categorie: "bezienswaardigheden",
          duur: "1–2 uur",
          kosten: "Rp 20.000",
          tip: "Neem de lift naar de top voor panoramisch uitzicht over Jakarta. 's Morgens vroeg voor minder wachtrij.",
          mapsUrl: "https://maps.google.com/?q=Monas+Jakarta",
        },
        {
          naam: "Pasar Santa",
          categorie: "winkelen",
          duur: "1–2 uur",
          kosten: "variabel",
          tip: "Hippe markthal met streetfood, vintage kleding en lokale kunstenaars. Populair bij jonge Jakartanen.",
          mapsUrl: "https://maps.google.com/?q=Pasar+Santa+Jakarta",
        },
      ],
      restaurants: [
        {
          naam: "Namaaz Dining",
          keuken: "Indonesisch moleculair",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          adres: "Jl. Sriwijaya I No.40, Kebayoran Baru, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Namaaz+Dining+Jakarta",
          reservering: true,
          openingstijden: "18:30–23:00 (di–za)",
          tip: "Indonesische moleculaire gastronomie op topniveau. 16 verrassingsgerechten. Weken van tevoren reserveren.",
        },
        {
          naam: "Sate Khas Senayan",
          keuken: "Indonesisch",
          sfeer: "authentiek",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Kebon Sirih No.31A, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Sate+Khas+Senayan+Jakarta",
          reservering: false,
          openingstijden: "10:00–22:00",
          tip: "Beste sate van Jakarta. Bestel de sate kambing (geit). Contant betalen.",
        },
        {
          naam: "Café Batavia",
          keuken: "Internationaal / Koloniaal",
          sfeer: "historisch",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Pintu Besar Utara No.14, Kota Tua, Jakarta",
          mapsUrl: "https://maps.google.com/?q=Cafe+Batavia+Jakarta",
          reservering: false,
          openingstijden: "09:00–24:00",
          tip: "Iconisch koloniaal pand uit 1805 op het Fatahillah-plein. Perfect voor lunch na Kota Tua bezoek.",
        },
        {
          naam: "Warung Nasi Ampera",
          keuken: "Sundanees",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Meerdere locaties in Jakarta",
          mapsUrl: "https://maps.google.com/?q=Warung+Nasi+Ampera+Jakarta",
          reservering: false,
          openingstijden: "08:00–22:00",
          tip: "Authentiek Sundanees eten. Wijs gewoon naar wat je wilt. Lokale favoriet, spotgoedkoop.",
        },
      ],
    },
    {
      id: "yogyakarta",
      stad: "Yogyakarta",
      land: "Indonesië",
      type: "cultuur",
      emoji: "🏯",
      datums: {
        aankomst: "2026-07-17",
        vertrek: "2026-07-20",
      },
      hotel: {
        naam: "Vul je hotel in",
        adres: "Yogyakarta, Java",
        mapsUrl: "https://maps.google.com/?q=Yogyakarta",
        telefoon: "+62 ...",
        checkIn: "14:00",
        checkOut: "12:00",
        boekingsnummer: "VUL-IN",
        bron: "booking.com",
        nachten: 3,
        opmerkingen: "Vul je eigen hotelgegevens in",
      },
      vervoer: {
        aankomst: {
          type: "vlucht",
          van: "Jakarta CGK",
          vluchtnummer: "VLUCHT-NR",
          aankomstTijd: "2026-07-17T11:00:00",
          boekingsnummer: "VLUCHT-REF",
          opmerkingen: "Yogyakarta International Airport (YIA) — taxi naar hotel ~45 min",
        },
        vertrek: {
          type: "vlucht",
          naar: "Bali DPS",
          vluchtnummer: "VLUCHT-NR",
          vertrekTijd: "2026-07-20T10:00:00",
          boekingsnummer: "VLUCHT-REF",
          opmerkingen: "Check-in 2 uur voor vertrek",
        },
      },
      activiteiten: [
        {
          naam: "Borobudur Tempel",
          categorie: "cultuur",
          duur: "3–4 uur",
          kosten: "Rp 350.000",
          tip: "Ga bij zonsopgang voor het mooiste licht en minder bezoekers. Gids aanbevolen voor context. 40 km van Yogya.",
          mapsUrl: "https://maps.google.com/?q=Borobudur+Temple",
        },
        {
          naam: "Prambanan Tempel Complex",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "Rp 350.000",
          tip: "Indrukwekkend Hindoe-tempelcomplex. Combineer combiticket met Borobudur voor korting.",
          mapsUrl: "https://maps.google.com/?q=Prambanan+Temple",
        },
        {
          naam: "Kraton (Sultanspaleis)",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "Rp 15.000",
          tip: "Nog steeds bewoond door de sultan. Dansvoorstellingen op vaste tijden. Batik workshops in de buurt.",
          mapsUrl: "https://maps.google.com/?q=Kraton+Yogyakarta",
        },
        {
          naam: "Jalan Malioboro",
          categorie: "winkelen",
          duur: "2 uur",
          kosten: "variabel",
          tip: "Hoofdwinkelstraat van Yogya. 's Avonds gezelligst. Batik, leer, wayang poppen en souvenirs.",
          mapsUrl: "https://maps.google.com/?q=Jalan+Malioboro+Yogyakarta",
        },
        {
          naam: "Mount Merapi Jeep Tour",
          categorie: "avontuur",
          duur: "halve dag",
          kosten: "~Rp 400.000 p.p.",
          tip: "Jeep-tour over lavas tromen van de actieve vulkaan. Boek een dag van tevoren via hotel. Spectaculair.",
          mapsUrl: "https://maps.google.com/?q=Mount+Merapi+Yogyakarta",
        },
      ],
      restaurants: [
        {
          naam: "Bale Raos",
          keuken: "Javaans Paleis",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Magangan Kulon No.1, Kraton, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Bale+Raos+Yogyakarta",
          reservering: true,
          openingstijden: "11:00–21:00",
          tip: "Gerechten uit de eeuwenoude sultanskeukens van het Kraton. Bijzondere, authentieke ervaring. Reserveer vooraf.",
        },
        {
          naam: "Gudeg Yu Djum",
          keuken: "Javaans",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Jl. Kaliurang KM 4.5, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Gudeg+Yu+Djum+Yogyakarta",
          reservering: false,
          openingstijden: "06:00–14:00",
          tip: "Beste gudeg (gestoofde jackfruit) van Yogya. Legendarisch. Kom vroeg want het is snel op.",
        },
        {
          naam: "Via Via Restaurant",
          keuken: "Indonesisch / Internationaal",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Prawirotaman I No.30, Yogyakarta",
          mapsUrl: "https://maps.google.com/?q=Via+Via+Restaurant+Yogyakarta",
          reservering: false,
          openingstijden: "08:00–23:00",
          tip: "Gezellig terras in Prawirotaman. Goede cocktails. Culturele optredens in de avond.",
        },
      ],
    },
    {
      id: "ubud",
      stad: "Ubud",
      land: "Bali",
      type: "natuur",
      emoji: "🌿",
      datums: {
        aankomst: "2026-07-20",
        vertrek: "2026-07-26",
      },
      hotel: {
        naam: "Vul je hotel in",
        adres: "Ubud, Bali",
        mapsUrl: "https://maps.google.com/?q=Ubud+Bali",
        telefoon: "+62 ...",
        checkIn: "14:00",
        checkOut: "11:00",
        boekingsnummer: "VUL-IN",
        bron: "booking.com",
        nachten: 6,
        opmerkingen: "Vul je eigen hotelgegevens in",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Bali DPS (vliegveld)",
          opmerkingen: "~1,5 uur rijden. Hotel shuttle of Bluebird taxi aanbevolen. Prijs ~Rp 250.000.",
        },
        vertrek: {
          type: "auto",
          naar: "Seminyak",
          opmerkingen: "~1 uur rijden. Private driver of taxi.",
        },
      },
      activiteiten: [
        {
          naam: "Tegallalang Rijstterrassen",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "~Rp 15.000",
          tip: "Vroeg gaan (7:00) voor drukte en hitte. Indrukwekkende terrassen. Lokale donaties worden gevraagd.",
          mapsUrl: "https://maps.google.com/?q=Tegallalang+Rice+Terrace",
        },
        {
          naam: "Ubud Monkey Forest",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "Rp 80.000",
          tip: "Geen eten meenemen. Telefoon en zonnebril in tas bij apen in de buurt. Rustgevend bos.",
          mapsUrl: "https://maps.google.com/?q=Ubud+Monkey+Forest",
        },
        {
          naam: "Kecak Dans bij Uluwatu",
          categorie: "cultuur",
          duur: "2 uur + reistijd",
          kosten: "Rp 100.000",
          tip: "Zonsondergangsshow om 18:00. Kaartjes ter plaatse kopen. 1 uur rijden vanuit Ubud. Spectaculair.",
          mapsUrl: "https://maps.google.com/?q=Uluwatu+Temple+Bali",
        },
        {
          naam: "Kookles",
          categorie: "cultuur",
          duur: "4–5 uur",
          kosten: "~Rp 400.000 p.p.",
          tip: "Inclusief marktbezoek. Paon Bali of Casa Luna zijn topkeuzes. Minstens een dag van tevoren boeken.",
          mapsUrl: "https://maps.google.com/?q=Paon+Bali+Cooking+Class",
        },
        {
          naam: "Campuhan Ridge Walk",
          categorie: "natuur",
          duur: "1–2 uur",
          kosten: "gratis",
          tip: "Prachtige wandeling over bergrug door rijstvelden. Vertrek bij zonsopgang vanuit Jl. Raya Campuhan.",
          mapsUrl: "https://maps.google.com/?q=Campuhan+Ridge+Walk+Ubud",
        },
        {
          naam: "Tirta Empul Tempel",
          categorie: "cultuur",
          duur: "1–2 uur",
          kosten: "Rp 50.000",
          tip: "Heilig tempelcomplex met reinigingsritueel in heilig bronwater. Sarong verplicht (huur ter plaatse).",
          mapsUrl: "https://maps.google.com/?q=Tirta+Empul+Temple+Bali",
        },
      ],
      restaurants: [
        {
          naam: "Locavore",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          adres: "Jl. Dewisita No.10, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Locavore+Ubud",
          reservering: true,
          openingstijden: "12:00–14:30 & 18:30–22:30 (di–zo)",
          tip: "Meerdere keren in de top 50 beste restaurants van Azië. Seizoensgebonden tasting menu met lokale ingrediënten. Weken vooruit boeken — absoluut een must.",
        },
        {
          naam: "Room4Dessert",
          keuken: "Dessert tasting menu",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Sanggingan, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Room4Dessert+Ubud",
          reservering: true,
          openingstijden: "18:00–23:00",
          tip: "Van de beroemde chef Will Goldfarb. Alleen desserts en cocktails. Unieke, verrassende ervaring.",
        },
        {
          naam: "Warung Babi Guling Ibu Oka",
          keuken: "Balinese BBQ",
          sfeer: "lokaal",
          prijsniveau: "€",
          michelin: 0,
          adres: "Jl. Suweta No.2, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Ibu+Oka+Babi+Guling+Ubud",
          reservering: false,
          openingstijden: "11:00–15:00",
          tip: "Beroemde geroosterde biggetjes (babi guling). Anthony Bourdain at hier. Op = op, dus vroeg gaan.",
        },
        {
          naam: "Naughty Nuri's",
          keuken: "BBQ ribben",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Raya Sanggingan No.135, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=Naughty+Nuris+Ubud",
          reservering: false,
          openingstijden: "11:00–22:00",
          tip: "Legendarische spareribs en sterke martini's. Een Ubud-instelling die je niet mag overslaan.",
        },
        {
          naam: "Swept Away (COMO Uma Ubud)",
          keuken: "Internationaal",
          sfeer: "romantisch",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Raya Sanggingan, Ubud, Bali",
          mapsUrl: "https://maps.google.com/?q=COMO+Uma+Ubud",
          reservering: false,
          openingstijden: "07:00–22:00",
          tip: "Prachtig zwembadrestaurant midden in de jungle. Perfect voor een romantisch diner.",
        },
      ],
    },
    {
      id: "seminyak",
      stad: "Seminyak",
      land: "Bali",
      type: "strand",
      emoji: "🌊",
      datums: {
        aankomst: "2026-07-26",
        vertrek: "2026-08-01",
      },
      hotel: {
        naam: "Vul je hotel in",
        adres: "Seminyak, Bali",
        mapsUrl: "https://maps.google.com/?q=Seminyak+Bali",
        telefoon: "+62 ...",
        checkIn: "15:00",
        checkOut: "12:00",
        boekingsnummer: "VUL-IN",
        bron: "booking.com",
        nachten: 6,
        opmerkingen: "Vul je eigen hotelgegevens in",
      },
      vervoer: {
        aankomst: {
          type: "auto",
          van: "Ubud",
          opmerkingen: "~1 uur rijden. Private driver of taxi.",
        },
        vertrek: {
          type: "vlucht",
          naar: "Amsterdam AMS",
          vluchtnummer: "VLUCHT-NR",
          vertrekTijd: "2026-08-01T14:00:00",
          boekingsnummer: "VLUCHT-REF",
          opmerkingen: "Ngurah Rai Airport (DPS). Vertrek hotel uiterlijk om 11:00.",
        },
      },
      activiteiten: [
        {
          naam: "Seminyak Strand & Zonsondergang",
          categorie: "natuur",
          duur: "2 uur",
          kosten: "gratis",
          tip: "Loop richting Petitenget voor minder drukte. Zonsondergang rond 18:30. Spectaculaire kleuren.",
          mapsUrl: "https://maps.google.com/?q=Seminyak+Beach+Bali",
        },
        {
          naam: "Potato Head Beach Club",
          categorie: "bezienswaardigheden",
          duur: "3–5 uur",
          kosten: "min. besteding ~Rp 200.000",
          tip: "Reserveer een daybed vooraf. Aanwezig om 14:00 voor de beste plekken. Iconische plek.",
          mapsUrl: "https://maps.google.com/?q=Potato+Head+Beach+Club+Bali",
        },
        {
          naam: "Tanah Lot Tempel",
          categorie: "cultuur",
          duur: "2–3 uur",
          kosten: "Rp 60.000",
          tip: "Iconische zeerotstempel bij zonsondergang. 30 minuten rijden van Seminyak. Erg fotogeniek.",
          mapsUrl: "https://maps.google.com/?q=Tanah+Lot+Temple+Bali",
        },
        {
          naam: "Surfles op Kuta Beach",
          categorie: "avontuur",
          duur: "2 uur",
          kosten: "~Rp 200.000 incl. board",
          tip: "Kuta is perfect voor beginners. Veel instructeurs op het strand. Surfboard huren kan ook zelfstandig.",
          mapsUrl: "https://maps.google.com/?q=Kuta+Beach+Bali",
        },
        {
          naam: "Pasar Seminyak (Avondmarkt)",
          categorie: "winkelen",
          duur: "1–2 uur",
          kosten: "variabel",
          tip: "'s Avonds het levendigst. Onderhandel tot 50% van de vraagprijs. Sarongs, handwerk en cadeaus.",
          mapsUrl: "https://maps.google.com/?q=Pasar+Seminyak",
        },
      ],
      restaurants: [
        {
          naam: "Sarong Restaurant",
          keuken: "Pan-Aziatisch",
          sfeer: "fine dining",
          prijsniveau: "€€€€",
          michelin: 0,
          adres: "Jl. Petitenget No.19X, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Sarong+Restaurant+Seminyak",
          reservering: true,
          openingstijden: "18:30–23:00",
          tip: "Een van de mooiste restaurants van Bali. Prachtig interieur. 12-gerechten degustatiemenu beschikbaar. Reserveer ver vooraf.",
        },
        {
          naam: "Merah Putih",
          keuken: "Modern Indonesisch",
          sfeer: "fine dining",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Petitenget No.100X, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Merah+Putih+Seminyak",
          reservering: true,
          openingstijden: "12:00–23:00",
          tip: "Spectaculair bamboe interieur van 8 meter hoog. Indonesische gerechten met moderne twist. Heerlijke cocktails.",
        },
        {
          naam: "La Lucciola",
          keuken: "Mediterraans",
          sfeer: "romantisch",
          prijsniveau: "€€€",
          michelin: 0,
          adres: "Jl. Petitenget, Seminyak Beach, Bali",
          mapsUrl: "https://maps.google.com/?q=La+Lucciola+Seminyak",
          reservering: true,
          openingstijden: "11:00–23:00",
          tip: "Direct aan het strand. Perfect voor zonsondergang diner. Vraag om een tafel aan het raam.",
        },
        {
          naam: "Fat Chow",
          keuken: "Aziatisch fusion",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Laksmana No.47, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Fat+Chow+Seminyak",
          reservering: false,
          openingstijden: "12:00–23:00",
          tip: "Lekker voor lunch of vroeg diner. Goede dim sum en wok-gerechten. Betaalbaar.",
        },
        {
          naam: "Warung Italia",
          keuken: "Italiaans",
          sfeer: "casual",
          prijsniveau: "€€",
          michelin: 0,
          adres: "Jl. Laksmana No.91, Seminyak, Bali",
          mapsUrl: "https://maps.google.com/?q=Warung+Italia+Seminyak",
          reservering: false,
          openingstijden: "12:00–22:00",
          tip: "Als je even genoeg hebt van rijst. Authentieke Italiaanse pasta. Lokale favoriet.",
        },
      ],
    },
  ],
};
